-- BluefinTecsMerchantPortal SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

namespace Merchant_portal_api_controller
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "merchant_portal_api_controller" d co
end Merchant_portal_api_controller

namespace Merchant_portal_common_controller
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "merchant_portal_common_controller" m co
end Merchant_portal_common_controller

namespace Merchant_portal_pam_contract_controller
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "merchant_portal_pam_contract_controller" d co
end Merchant_portal_pam_contract_controller

namespace Merchant_portal_pam_document_controller
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "merchant_portal_pam_document_controller" d co
end Merchant_portal_pam_document_controller

namespace Merchant_portal_pam_form_controller
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "merchant_portal_pam_form_controller" d co
end Merchant_portal_pam_form_controller

namespace Merchant_portal_pam_mandator_controller
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "merchant_portal_pam_mandator_controller" d co
end Merchant_portal_pam_mandator_controller

namespace Merchant_portal_pam_merchant_controller
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "merchant_portal_pam_merchant_controller" d co
end Merchant_portal_pam_merchant_controller

namespace Merchant_portal_pam_package_controller
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "merchant_portal_pam_package_controller" d co
end Merchant_portal_pam_package_controller

namespace Merchant_portal_pam_product_controller
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "merchant_portal_pam_product_controller" d co
end Merchant_portal_pam_product_controller

namespace Output_add_product
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_add_product" d co
end Output_add_product

namespace Output_create_product
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_create_product" d co
end Output_create_product

namespace Output_detail
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "output_detail" m co
end Output_detail

namespace Output_list
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_list" d co
end Output_list

namespace Output_message
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "output_message" m co
end Output_message

namespace Output_move_tid
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_move_tid" d co
end Output_move_tid

namespace Output_remove_product
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_remove_product" d co
end Output_remove_product

namespace Output_start
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_start" d co
end Output_start

namespace Output_status
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "output_status" m co
end Output_status

namespace Output_update_product
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "output_update_product" d co
end Output_update_product

