// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(1,
      "name", v_str("BluefinTecsMerchantPortal")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(3,
      "base", v_str("https://test.tecs.at"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(19,
        "merchant_portal_api_controller", v_map(),
        "merchant_portal_common_controller", v_map(),
        "merchant_portal_pam_contract_controller", v_map(),
        "merchant_portal_pam_document_controller", v_map(),
        "merchant_portal_pam_form_controller", v_map(),
        "merchant_portal_pam_mandator_controller", v_map(),
        "merchant_portal_pam_merchant_controller", v_map(),
        "merchant_portal_pam_package_controller", v_map(),
        "merchant_portal_pam_product_controller", v_map(),
        "output_add_product", v_map(),
        "output_create_product", v_map(),
        "output_detail", v_map(),
        "output_list", v_map(),
        "output_message", v_map(),
        "output_move_tid", v_map(),
        "output_remove_product", v_map(),
        "output_start", v_map(),
        "output_status", v_map(),
        "output_update_product", v_map())),
    "entity", cmap(19,
      "merchant_portal_api_controller", cmap(4,
        "fields", clist(33,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("account_number"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("additional_data"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("business_reg_number"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("city"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("corporateuuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("country"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("merchant_category_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("merchant_email"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("merchant_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("merchant_phone_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("packageid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("packageorderuuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("password"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("productid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("productid_acquirer"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reason_deactivation"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(16)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reason_reactivation"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(17)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting_code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(18)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("state"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(19)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(20)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminal_country_code"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(21)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminal_language_code"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(22)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminal_location"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(23)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminal_serial_number"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(24)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminalid"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(25)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminalid_acquirer"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(26)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("user_email"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(27)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("user_phone_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(28)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("username"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(29)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("vu_nummer"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(30)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("web_shop_url"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(31)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("zipcode"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(32))),
        "name", v_str("merchant_portal_api_controller"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/deactivateTerminal"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("deactivateTerminal")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/reactivateTerminal"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("reactivateTerminal")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerAdditionalTerminal"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerAdditionalTerminal")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(2)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerNewMerchant"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerNewMerchant")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(3))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_common_controller", cmap(4,
        "fields", v_list(),
        "name", v_str("merchant_portal_common_controller"),
        "op", cmap(1,
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(8,
                "active", v_bool(true),
                "args", v_map(),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/logDeveloperInfo"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("logDeveloperInfo")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", v_map(),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/version"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("version")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1))),
            "key$", v_str("load"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_contract_controller", cmap(4,
        "fields", clist(2,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("language"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_order_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1))),
        "name", v_str("merchant_portal_pam_contract_controller"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/generateContract"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("generateContract")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/uploadContract"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("uploadContract")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_document_controller", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("app_form_field_desc_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_order_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_order_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("merchant_portal_pam_document_controller"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/documentsList"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("documentsList")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/downloadDocument"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("downloadDocument")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_form_controller", cmap(4,
        "fields", clist(9,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("app_form_fields_desc_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("language"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_order"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(3)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("package_order_uuid"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_order"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(6)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("product_order_uuid"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reason_of_reopening"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(8))),
        "name", v_str("merchant_portal_pam_form_controller"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(6,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/applicationForm"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("applicationForm")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/packageForm"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("packageForm")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/reopenForm"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("reopenForm")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(2)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/secretKey"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("secretKey")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(3)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/submitForm"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("submitForm")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(4)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/submitValues"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("submitValues")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(5))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_mandator_controller", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("client_secret"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mandator_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("notification_email"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("merchant_portal_pam_mandator_controller"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(3,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/createMandatorConfig"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("createMandatorConfig")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/introduceMandatorPackage"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("introduceMandatorPackage")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/selfRegistrationLink"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("selfRegistrationLink")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(2))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_merchant_controller", cmap(4,
        "fields", clist(26,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("additional_data"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("business_registration_number"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("city"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("company_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("corporate_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("country"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("email"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("language"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("login"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("mandator"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("merchant_category_code"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("merchant_contract_number"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("merchant_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("packageorderuuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("phone_number"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(16)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("postal_code"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(17)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("productid_acquirer"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(18)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("region"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(19)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("registration_number"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(20)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("signature"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(21)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("street"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(22)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminal_id"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(23)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminalid_acquirer"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(24)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("vu_nummer"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(25))),
        "name", v_str("merchant_portal_pam_merchant_controller"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/contractNumber"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("contractNumber")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerAdditionalAcquiring"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerAdditionalAcquiring")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/updateMerchant"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("updateMerchant")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(2)),
              cmap(8,
                "active", v_bool(true),
                "args", v_map(),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerMerchant"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerMerchant")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(3))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_package_controller", cmap(4,
        "fields", clist(11,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("corporate_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("country"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("description_key"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(4)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("language"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name_key"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_status"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(10))),
        "name", v_str("merchant_portal_pam_package_controller"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(5,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/availablePackages"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("availablePackages")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/orderPackage"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("orderPackage")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/orderedPackages"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("orderedPackages")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(2)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/packageTemplates"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("packageTemplates")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(3)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/updatePackageData"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("updatePackageData")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(4))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_product_controller", cmap(4,
        "fields", clist(10,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("consumer_uuid"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("filter"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("language"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("merchant_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_order_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_order_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("reason_decline"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(9))),
        "name", v_str("merchant_portal_pam_product_controller"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/approveProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("approveProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/declineProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("declineProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/orderAdditionalProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("orderAdditionalProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(2)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/productsList"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("productsList")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(3))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_add_product", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_uui_d"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_add_product"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/addProductsToPackage"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("addProductsToPackage")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_create_product", cmap(4,
        "fields", clist(14,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("acquirer_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("allow_multiple_order"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("app_form_template_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("contract_needed"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("credentials_needed"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("description_key"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name_key"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("prescreening_allowed"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("terminal_template_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("vendor_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("xml_template_file"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(13))),
        "name", v_str("output_create_product"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/createNewProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("createNewProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_detail", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("detail"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_detail"),
        "op", cmap(1,
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(2,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(7,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"),
                      "index$", v_num(0)))),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/details/{id}"),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("details"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("load"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list", cmap(4,
        "fields", clist(5,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("item"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(0)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("pagination"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$OBJECT`"))),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("sorting"),
            "req", v_bool(false),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(4))),
        "name", v_str("output_list"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/list"),
                "parts", clist(4,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("list")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_message", cmap(4,
        "fields", clist(2,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(1))),
        "name", v_str("output_message"),
        "op", cmap(1,
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(2,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/restart/{id}"),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("restart"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", cmap(2,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/stop/{id}"),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("stop"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1))),
            "key$", v_str("load"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_move_tid", cmap(4,
        "fields", clist(5,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_order_uui_d"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("target_package_order_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("target_product_order_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(4))),
        "name", v_str("output_move_tid"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/moveTid"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("moveTid")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_remove_product", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("package_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_uui_d"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_remove_product"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/removeProductsFromPackage"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("removeProductsFromPackage")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_start", cmap(4,
        "fields", clist(3,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2))),
        "name", v_str("output_start"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/start"),
                "parts", clist(4,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("start")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_status", cmap(4,
        "fields", clist(4,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("percentage"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("status"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3))),
        "name", v_str("output_status"),
        "op", cmap(1,
          "load", cmap(4,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(2,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/status/{id}"),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("status"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("load"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_update_product", cmap(4,
        "fields", clist(13,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("allow_multiple_order"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("app_form_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("contract_needed"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("credentials_needed"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("description_key"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name_key"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("prescreening_allowed"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_status"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("product_uuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("response_message"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("vendor_name"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(12))),
        "name", v_str("output_update_product"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "header", clist(1,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/updateProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("updateProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

Feature* make_feature(const char* name) {
  if (strcmp(name, "audit") == 0) return feature_audit_new();
  if (strcmp(name, "cache") == 0) return feature_cache_new();
  if (strcmp(name, "clienttrack") == 0) return feature_clienttrack_new();
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "log") == 0) return feature_log_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "netsim") == 0) return feature_netsim_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "proxy") == 0) return feature_proxy_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "rbac") == 0) return feature_rbac_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "streaming") == 0) return feature_streaming_new();
  if (strcmp(name, "telemetry") == 0) return feature_telemetry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}
