// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(1,
      "name", v_str("BluefinTecsMerchantPortal")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(3,
      "base", v_str("https://test.tecs.at"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(19,
        "merchant_portal_api_controller", v_map(),
        "merchant_portal_common_controller", v_map(),
        "merchant_portal_pam_contract_controller", v_map(),
        "merchant_portal_pam_document_controller", v_map(),
        "merchant_portal_pam_form_controller", v_map(),
        "merchant_portal_pam_mandator_controller", v_map(),
        "merchant_portal_pam_merchant_controller", v_map(),
        "merchant_portal_pam_package_controller", v_map(),
        "merchant_portal_pam_product_controller", v_map(),
        "output_add_product", v_map(),
        "output_create_product", v_map(),
        "output_detail", v_map(),
        "output_list", v_map(),
        "output_message", v_map(),
        "output_move_tid", v_map(),
        "output_remove_product", v_map(),
        "output_start", v_map(),
        "output_status", v_map(),
        "output_update_product", v_map())),
    "entity", cmap(19,
      "merchant_portal_api_controller", cmap(4,
        "fields", clist(33,
          cmap(2,
            "name", v_str("account_number"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("additional_data"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("business_reg_number"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("city"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("corporateuuid"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("country"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("merchant_category_code"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("merchant_email"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("merchant_name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchant_phone_number"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageorderuuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("password"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("productid"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("productid_acquirer"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reason_deactivation"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reason_reactivation"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sorting_code"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("state"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("street"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminal_country_code"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminal_language_code"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminal_location"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminal_serial_number"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalid"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("terminalid_acquirer"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("user_email"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("user_phone_number"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("username"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("vu_nummer"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("web_shop_url"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("zipcode"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_api_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/deactivateTerminal"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("deactivateTerminal")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/reactivateTerminal"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("reactivateTerminal")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerAdditionalTerminal"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerAdditionalTerminal")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerNewMerchant"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerNewMerchant")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_common_controller", cmap(4,
        "fields", v_list(),
        "name", v_str("merchant_portal_common_controller"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/logDeveloperInfo"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("logDeveloperInfo")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/version"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("version")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_contract_controller", cmap(4,
        "fields", clist(2,
          cmap(3,
            "name", v_str("language"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_contract_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/generateContract"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("generateContract")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/uploadContract"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("uploadContract")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_document_controller", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("appFormFieldDescUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("packageOrderUUID"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("productOrderUUID"),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_document_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/documentsList"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("documentsList")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/downloadDocument"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("downloadDocument")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_form_controller", cmap(4,
        "fields", clist(9,
          cmap(3,
            "name", v_str("appFormFieldsDescUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("filter"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("language"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("packageOrder"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("packageOrderUUID"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("packageUUID"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productOrderUUID"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("productOrders"),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("reasonOfReopening"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_form_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(6,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/applicationForm"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("applicationForm")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/packageForm"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("packageForm")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/reopenForm"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("reopenForm")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/secretKey"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("secretKey")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/submitForm"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("submitForm")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/submitValues"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("submitValues")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_mandator_controller", cmap(4,
        "fields", clist(4,
          cmap(2,
            "name", v_str("clientSecret"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("mandatorName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("notificationEmail"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_mandator_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(3,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/createMandatorConfig"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("createMandatorConfig")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/introduceMandatorPackage"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("introduceMandatorPackage")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/selfRegistrationLink"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("selfRegistrationLink")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_merchant_controller", cmap(4,
        "fields", clist(26,
          cmap(2,
            "name", v_str("additional_data"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("businessRegistrationNumber"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("city"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("companyName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("corporateUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("country"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("currency"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("email"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("language"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("login"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("mandator"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("merchantContractNumber"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchant_category_code"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("packageUUID"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageorderuuid"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("phoneNumber"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("postalCode"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productid_acquirer"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("region"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("registrationNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("signature"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("street"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("terminalIds"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("terminalid_acquirer"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("vu_nummer"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_merchant_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/contractNumber"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("contractNumber")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerAdditionalAcquiring"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerAdditionalAcquiring")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/updateMerchant"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("updateMerchant")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerMerchant"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerMerchant")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_package_controller", cmap(4,
        "fields", clist(11,
          cmap(2,
            "name", v_str("consumerUUID"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("corporateUUID"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("country"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("descriptionKey"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("filter"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("language"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("nameKey"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("packageStatus"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("merchant_portal_pam_package_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(5,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/availablePackages"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("availablePackages")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/orderPackage"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("orderPackage")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/orderedPackages"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("orderedPackages")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/packageTemplates"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("packageTemplates")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/updatePackageData"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("updatePackageData")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_product_controller", cmap(4,
        "fields", clist(10,
          cmap(2,
            "name", v_str("consumerUUID"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("filter"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("language"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantID"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("productOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("reason_decline"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("merchant_portal_pam_product_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/approveProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("approveProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/declineProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("declineProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/orderAdditionalProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("orderAdditionalProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/productsList"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("productsList")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_add_product", cmap(4,
        "fields", clist(4,
          cmap(3,
            "name", v_str("packageUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productUUIDs"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_add_product"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/addProductsToPackage"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("addProductsToPackage")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_create_product", cmap(4,
        "fields", clist(14,
          cmap(2,
            "name", v_str("acquirerId"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("allowMultipleOrders"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("appFormTemplateName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("contractNeeded"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("credentialsNeeded"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("descriptionKey"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("nameKey"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("prescreeningAllowed"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("productName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalTemplateName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("vendorName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("xmlTemplateFile"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_create_product"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/createNewProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("createNewProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_detail", cmap(4,
        "fields", clist(3,
          cmap(2,
            "name", v_str("batch"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("lines"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("progress"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("output_detail"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(2,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/details/{id}"),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("details"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list", cmap(4,
        "fields", clist(5,
          cmap(2,
            "name", v_str("items"),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("pagination"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$OBJECT`"))),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("output_list"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/list"),
                "parts", clist(4,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("list")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_message", cmap(4,
        "fields", clist(2,
          cmap(3,
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_message"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(7,
                "args", cmap(2,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/restart/{id}"),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("restart"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(2,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/stop/{id}"),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("stop"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_move_tid", cmap(4,
        "fields", clist(5,
          cmap(3,
            "name", v_str("productOrderUUIDs"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("targetPackageOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("targetProductOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_move_tid"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/moveTid"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("moveTid")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_remove_product", cmap(4,
        "fields", clist(4,
          cmap(3,
            "name", v_str("packageUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productUUIDs"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_remove_product"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/removeProductsFromPackage"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("removeProductsFromPackage")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_start", cmap(4,
        "fields", clist(3,
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_start"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/start"),
                "parts", clist(4,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("start")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_status", cmap(4,
        "fields", clist(4,
          cmap(2,
            "name", v_str("percentage"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("status"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_status"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(2,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/status/{id}"),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("status"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_update_product", cmap(4,
        "fields", clist(13,
          cmap(2,
            "name", v_str("allowMultipleOrders"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("appFormName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("contractNeeded"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("credentialsNeeded"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("descriptionKey"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("nameKey"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("prescreeningAllowed"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("productName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("productStatus"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("vendorName"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_update_product"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/updateProduct"),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("updateProduct")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
