// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("BluefinTecsMerchantPortal"),
      "slug", v_str("bluefin-tecs-merchant-portal"),
      "version", v_str("0.1.1"),
      "target", v_str("c")),
    "feature", cmap(11,
      "audit", cmap(2,
        "options", cmap(3,
          "active", v_bool(false),
          "actor", v_str("anonymous"),
          "max", v_num(1000)),
        "transport", v_str("none")),
      "clienttrack", cmap(2,
        "options", cmap(2,
          "active", v_bool(false),
          "clientVersion", v_str("0.0.1")),
        "transport", v_str("none")),
      "idempotency", cmap(2,
        "options", cmap(4,
          "active", v_bool(false),
          "header", v_str("Idempotency-Key"),
          "methods", clist(4,
            v_str("POST"),
            v_str("PUT"),
            v_str("PATCH"),
            v_str("DELETE")),
          "ops", clist(3,
            v_str("create"),
            v_str("update"),
            v_str("remove"))),
        "transport", v_str("none")),
      "log", cmap(2,
        "options", cmap(1,
          "active", v_bool(true)),
        "transport", v_str("none")),
      "metrics", cmap(2,
        "options", cmap(1,
          "active", v_bool(false)),
        "transport", v_str("none")),
      "paging", cmap(2,
        "options", cmap(7,
          "active", v_bool(false),
          "afterVar", v_str("after"),
          "cursorParam", v_str("cursor"),
          "firstVar", v_str("first"),
          "limitParam", v_str("limit"),
          "pageParam", v_str("page"),
          "startPage", v_num(1)),
        "transport", v_str("none")),
      "ratelimit", cmap(2,
        "options", cmap(3,
          "active", v_bool(false),
          "burst", v_num(5),
          "rate", v_num(5)),
        "transport", v_str("wrap")),
      "retry", cmap(2,
        "options", cmap(6,
          "active", v_bool(false),
          "factor", v_num(2),
          "maxDelay", v_num(2000),
          "minDelay", v_num(50),
          "retries", v_num(2),
          "statuses", clist(7,
            v_num(408),
            v_num(425),
            v_num(429),
            v_num(500),
            v_num(502),
            v_num(503),
            v_num(504))),
        "transport", v_str("wrap")),
      "telemetry", cmap(2,
        "options", cmap(1,
          "active", v_bool(false)),
        "transport", v_str("none")),
      "test", cmap(2,
        "options", cmap(1,
          "active", v_bool(false)),
        "transport", v_str("base")),
      "timeout", cmap(2,
        "options", cmap(2,
          "active", v_bool(false),
          "ms", v_num(30000)),
        "transport", v_str("wrap"))),
    "options", cmap(3,
      "base", v_str("https://test.tecs.at"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(19,
        "merchant_portal_api_controller", v_map(),
        "merchant_portal_common_controller", v_map(),
        "merchant_portal_pam_contract_controller", v_map(),
        "merchant_portal_pam_document_controller", v_map(),
        "merchant_portal_pam_form_controller", v_map(),
        "merchant_portal_pam_mandator_controller", v_map(),
        "merchant_portal_pam_merchant_controller", v_map(),
        "merchant_portal_pam_package_controller", v_map(),
        "merchant_portal_pam_product_controller", v_map(),
        "output_add_product", v_map(),
        "output_create_product", v_map(),
        "output_detail", v_map(),
        "output_list", v_map(),
        "output_message", v_map(),
        "output_move_tid", v_map(),
        "output_remove_product", v_map(),
        "output_start", v_map(),
        "output_status", v_map(),
        "output_update_product", v_map())),
    "entity", cmap(19,
      "merchant_portal_api_controller", cmap(4,
        "fields", clist(33,
          cmap(4,
            "format", v_str("int32"),
            "name", v_str("account_number"),
            "short", v_str("Account number provided by the acquirer."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("additional_data"),
            "short", v_str("Arbitrary merchant-specific data related to terminal registration."),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("business_reg_number"),
            "req", v_bool(true),
            "short", v_str("Merchant business registration number as stated in the company registry."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("city"),
            "req", v_bool(true),
            "short", v_str("Merchant's address: city."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("corporateuuid"),
            "short", v_str("Unique identifier for the corporate entity (UUID format)."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("country"),
            "req", v_bool(true),
            "short", v_str("Merchant's address: country (must be in 'ISO-3166 ALPHA-3' format)."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("currency"),
            "req", v_bool(true),
            "short", v_str("Transaction currency (must be in \"ISO 4217\" format)."),
            "type", v_str("`$STRING`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("merchant_category_code"),
            "req", v_bool(true),
            "short", v_str("Merchant category code as defined by the payment network."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "format", v_str("email"),
            "name", v_str("merchant_email"),
            "short", v_str("Merchant's email address for receiving notifications."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("merchant_name"),
            "req", v_bool(true),
            "short", v_str("The officially incorporated company name of the merchant."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("merchant_phone_number"),
            "short", v_str("Merchant's phone number for notifications."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("packageid"),
            "req", v_bool(true),
            "short", v_str("Identifier of the package in the TECS processing engine provided by TECS."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("packageorderuuid"),
            "req", v_bool(true),
            "short", v_str("Identifier of the registered merchant in the TECS system, provided in the response of the registerNewMerchant call."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("password"),
            "short", v_str("Merchant password for MPOS."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productid"),
            "short", v_str("Identifier of the product for which terminal registration is to be performed."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productid_acquirer"),
            "short", v_str("Identifier of the product for which acquiring is enabled."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("reason_deactivation"),
            "req", v_bool(true),
            "short", v_str("Reason for terminal deactivation."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("reason_reactivation"),
            "req", v_bool(true),
            "short", v_str("Reason for terminal reactivation."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "format", v_str("int32"),
            "name", v_str("sorting_code"),
            "short", v_str("Sorting code provided by the acquirer."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("state"),
            "short", v_str("Merchant's address: state."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("street"),
            "req", v_bool(true),
            "short", v_str("Merchant's address: street and house number."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("terminal_country_code"),
            "req", v_bool(true),
            "short", v_str("Terminal country code (must be in 'ISO-3166 ALPHA-3' format)."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("terminal_language_code"),
            "req", v_bool(true),
            "short", v_str("Terminal language code (must be in 'ISO 639-1' format)."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("terminal_location"),
            "req", v_bool(true),
            "short", v_str("Physical or logical location of the terminal."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("terminal_serial_number"),
            "req", v_bool(true),
            "short", v_str("Terminal serial number."),
            "type", v_str("`$STRING`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("terminalid"),
            "req", v_bool(true),
            "short", v_str("TECS terminalid given by Tecs processing engine."),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("terminalid_acquirer"),
            "short", v_str("Terminal ID as set by the acquirer (optional)."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "format", v_str("email"),
            "name", v_str("user_email"),
            "short", v_str("Email address of the user acting on behalf of the merchant."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("user_phone_number"),
            "short", v_str("Phone number of the user acting on behalf of the merchant."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("username"),
            "short", v_str("Merchant username for MPOS."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("vu_nummer"),
            "req", v_bool(true),
            "short", v_str("Merchant contract number with the acquirer."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "format", v_str("uri"),
            "name", v_str("web_shop_url"),
            "short", v_str("URL of the merchant's web shop."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("zipcode"),
            "req", v_bool(true),
            "short", v_str("Merchant's address: postal code."),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_api_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/deactivateTerminal"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("deactivateTerminal"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("deactivateTerminal"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/reactivateTerminal"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("reactivateTerminal"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("reactivateTerminal"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerAdditionalTerminal"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("registerAdditionalTerminal"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerAdditionalTerminal"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerNewMerchant"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("registerNewMerchant"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerNewMerchant")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_common_controller", cmap(4,
        "fields", v_list(),
        "name", v_str("merchant_portal_common_controller"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/logDeveloperInfo"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("logDeveloperInfo"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("logDeveloperInfo"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/version"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("version"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("version")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_contract_controller", cmap(4,
        "fields", clist(2,
          cmap(3,
            "name", v_str("language"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_contract_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/generateContract"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("generateContract"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("generateContract"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/uploadContract"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("uploadContract"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("uploadContract")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_document_controller", cmap(4,
        "fields", clist(3,
          cmap(3,
            "name", v_str("appFormFieldDescUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageOrderUUID"),
            "short", v_str("UUID of the package order."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productOrderUUID"),
            "short", v_str("UUID of the product order."),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_document_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/documentsList"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("documentsList"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("documentsList"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/downloadDocument"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("downloadDocument"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("downloadDocument")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_form_controller", cmap(4,
        "fields", clist(9,
          cmap(3,
            "name", v_str("appFormFieldsDescUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("filter"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("language"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("packageOrder"),
            "type", v_str("`$OBJECT`")),
          cmap(5,
            "name", v_str("packageOrderUUID"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "short", v_str("UUID of the package order."),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("packageUUID"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("productOrderUUID"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "short", v_str("UUID of the product order."),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("productOrders"),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("reasonOfReopening"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_form_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(6,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/applicationForm"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("applicationForm"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("applicationForm"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/packageForm"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("packageForm"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("packageForm"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/reopenForm"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("reopenForm"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("reopenForm"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/secretKey"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("secretKey"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("secretKey"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/submitForm"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("submitForm"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("submitForm"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/submitValues"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("submitValues"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("submitValues")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_mandator_controller", cmap(4,
        "fields", clist(4,
          cmap(2,
            "name", v_str("clientSecret"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("mandatorName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("notificationEmail"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_mandator_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(3,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/createMandatorConfig"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("createMandatorConfig"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("createMandatorConfig"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/introduceMandatorPackage"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("introduceMandatorPackage"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("introduceMandatorPackage"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/selfRegistrationLink"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("selfRegistrationLink"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("selfRegistrationLink")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_merchant_controller", cmap(4,
        "fields", clist(26,
          cmap(3,
            "name", v_str("additional_data"),
            "short", v_str("Optional additional merchant-specific data related to enabling acquiring."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("businessRegistrationNumber"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("city"),
            "short", v_str("City where the merchant is located."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("companyName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("corporateUUID"),
            "req", v_bool(true),
            "short", v_str("Unique identifier for the corporate entity."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("country"),
            "short", v_str("Country where the merchant is located."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("currency"),
            "req", v_bool(true),
            "short", v_str("Transaction currency in ISO 4217 format."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("email"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("language"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("login"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("mandator"),
            "req", v_bool(true),
            "short", v_str("Mandator name assigned by TECS."),
            "type", v_str("`$STRING`")),
          cmap(5,
            "name", v_str("merchantContractNumber"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "short", v_str("Unique identifier for the merchant within a specific system."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("merchantName"),
            "short", v_str("Name of the merchant."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("merchant_category_code"),
            "short", v_str("Merchant Category Code (MCC) describing the merchant’s type of business."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageUUID"),
            "short", v_str("UUID of the package."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("packageorderuuid"),
            "req", v_bool(true),
            "short", v_str("Unique identifier for the registered merchant in the TECS system."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("phoneNumber"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("postalCode"),
            "short", v_str("Postal or ZIP code of the merchant’s location."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("productid_acquirer"),
            "req", v_bool(true),
            "short", v_str("Identifier of the product for which acquiring is to be enabled."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("region"),
            "short", v_str("State or province where the merchant is located."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("registrationNumber"),
            "short", v_str("Business registration number."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("signature"),
            "short", v_str("Signature value = saltAsHex-hashAsHex."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("street"),
            "short", v_str("Street address of the merchant."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("terminalIds"),
            "short", v_str("Optional list of terminal IDs for which acquiring should be activated."),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("terminalid_acquirer"),
            "short", v_str("Optional terminal ID provided by the acquirer."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("vu_nummer"),
            "req", v_bool(true),
            "short", v_str("Merchant contract number with the acquirer."),
            "type", v_str("`$STRING`"))),
        "name", v_str("merchant_portal_pam_merchant_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/contractNumber"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("contractNumber"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("contractNumber"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerAdditionalAcquiring"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("registerAdditionalAcquiring"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerAdditionalAcquiring"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/updateMerchant"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("updateMerchant"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("updateMerchant"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/registerMerchant"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("registerMerchant"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("registerMerchant")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_package_controller", cmap(4,
        "fields", clist(11,
          cmap(2,
            "name", v_str("consumerUUID"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("corporateUUID"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("country"),
            "short", v_str("Country associated with the package."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("descriptionKey"),
            "short", v_str("Key for the description of the package."),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("filter"),
            "type", v_str("`$OBJECT`")),
          cmap(4,
            "name", v_str("language"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("nameKey"),
            "short", v_str("Key for the name of the package."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageStatus"),
            "short", v_str("Status of the package."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("packageUUID"),
            "req", v_bool(true),
            "short", v_str("Unique identifier for the package."),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("merchant_portal_pam_package_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(5,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/availablePackages"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("availablePackages"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("availablePackages"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/orderPackage"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("orderPackage"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("orderPackage"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/orderedPackages"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("orderedPackages"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("orderedPackages"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/packageTemplates"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("packageTemplates"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("packageTemplates"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(4,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/updatePackageData"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("updatePackageData"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("updatePackageData")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "merchant_portal_pam_product_controller", cmap(4,
        "fields", clist(10,
          cmap(2,
            "name", v_str("consumerUUID"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("filter"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("language"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("merchantID"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("packageOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("pagination"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("productOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("reason_decline"),
            "req", v_bool(true),
            "short", v_str("Reason for product decline."),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("merchant_portal_pam_product_controller"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(4,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/approveProduct"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("approveProduct"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("approveProduct"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/declineProduct"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("declineProduct"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("declineProduct"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/orderAdditionalProduct"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("orderAdditionalProduct"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("orderAdditionalProduct"))),
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/productsList"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("productsList"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("productsList")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_add_product", cmap(4,
        "fields", clist(4,
          cmap(4,
            "name", v_str("packageUUID"),
            "req", v_bool(true),
            "short", v_str("Unique identifier for the package."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("productUUIDs"),
            "req", v_bool(true),
            "short", v_str("The list of unique identifiers of the products."),
            "type", v_str("`$ARRAY`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "short", v_str("Response code."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "short", v_str("Response message."),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_add_product"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/addProductsToPackage"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("addProductsToPackage"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("addProductsToPackage")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_create_product", cmap(4,
        "fields", clist(14,
          cmap(3,
            "name", v_str("acquirerId"),
            "short", v_str("Unique identifier for the acquirer."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("allowMultipleOrders"),
            "req", v_bool(true),
            "short", v_str("Indication whether multiple orders are allowed or not."),
            "type", v_str("`$BOOLEAN`")),
          cmap(4,
            "name", v_str("appFormTemplateName"),
            "req", v_bool(true),
            "short", v_str("Name of the application form template."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("contractNeeded"),
            "req", v_bool(true),
            "short", v_str("Indication whether contract is needed or not."),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("credentialsNeeded"),
            "short", v_str("Indication whether credentials are needed or not."),
            "type", v_str("`$BOOLEAN`")),
          cmap(4,
            "name", v_str("descriptionKey"),
            "req", v_bool(true),
            "short", v_str("Key indicator for product description."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("nameKey"),
            "req", v_bool(true),
            "short", v_str("Key indicator for product name."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("prescreeningAllowed"),
            "req", v_bool(true),
            "short", v_str("Indication whether prescreening is allowed or not."),
            "type", v_str("`$BOOLEAN`")),
          cmap(4,
            "name", v_str("productName"),
            "req", v_bool(true),
            "short", v_str("Name of the product."),
            "type", v_str("`$STRING`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "short", v_str("Response code."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "short", v_str("Response message."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("terminalTemplateName"),
            "req", v_bool(true),
            "short", v_str("Name of the terminal template."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("vendorName"),
            "req", v_bool(true),
            "short", v_str("Name of the vendor."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("xmlTemplateFile"),
            "req", v_bool(true),
            "short", v_str("A string value containing the XML template file encoded in Base64."),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_create_product"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/createNewProduct"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("createNewProduct"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("createNewProduct")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_detail", cmap(5,
        "fields", clist(4,
          cmap(2,
            "name", v_str("batch"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("lines"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("progress"),
            "type", v_str("`$OBJECT`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("output_detail"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(2,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/details/{id}"),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "lit", v_str("registerAdditionalTerminal")),
                  cmap(1,
                    "lit", v_str("details")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.details`")),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("details"),
                  v_str("{id}")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_list", cmap(4,
        "fields", clist(5,
          cmap(2,
            "name", v_str("items"),
            "type", v_str("`$ARRAY`")),
          cmap(4,
            "name", v_str("pagination"),
            "op", cmap(1,
              "create", cmap(1,
                "type", v_str("`$OBJECT`"))),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "short", v_str("Response code."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "short", v_str("Response message."),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("sorting"),
            "type", v_str("`$OBJECT`"))),
        "name", v_str("output_list"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/list"),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "lit", v_str("registerAdditionalTerminal")),
                  cmap(1,
                    "lit", v_str("list"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(4,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("list")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_message", cmap(5,
        "fields", clist(3,
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "short", v_str("Response code."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "short", v_str("Response message."),
            "type", v_str("`$STRING`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("output_message"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(8,
                "args", cmap(2,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/restart/{id}"),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "lit", v_str("registerAdditionalTerminal")),
                  cmap(1,
                    "lit", v_str("restart")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("restart"),
                  v_str("{id}"))),
              cmap(8,
                "args", cmap(2,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/stop/{id}"),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "lit", v_str("registerAdditionalTerminal")),
                  cmap(1,
                    "lit", v_str("stop")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("stop"),
                  v_str("{id}")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_move_tid", cmap(4,
        "fields", clist(5,
          cmap(3,
            "name", v_str("productOrderUUIDs"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "short", v_str("Response code."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "short", v_str("Response message."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("targetPackageOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("targetProductOrderUUID"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_move_tid"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/moveTid"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("moveTid"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("moveTid")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_remove_product", cmap(4,
        "fields", clist(4,
          cmap(4,
            "name", v_str("packageUUID"),
            "req", v_bool(true),
            "short", v_str("Unique identifier for the package."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("productUUIDs"),
            "req", v_bool(true),
            "short", v_str("List of product unique identifiers."),
            "type", v_str("`$ARRAY`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "short", v_str("Response code."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "short", v_str("Response message."),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_remove_product"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/removeProductsFromPackage"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("removeProductsFromPackage"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("removeProductsFromPackage")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_start", cmap(5,
        "fields", clist(3,
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "short", v_str("Response code."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "short", v_str("Response message."),
            "type", v_str("`$STRING`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("output_start"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/start"),
                "segments", clist(4,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "lit", v_str("registerAdditionalTerminal")),
                  cmap(1,
                    "lit", v_str("start"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(4,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("start")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_status", cmap(5,
        "fields", clist(5,
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "format", v_str("int32"),
            "name", v_str("percentage"),
            "type", v_str("`$INTEGER`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "short", v_str("Response code."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "short", v_str("Response message."),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("status"),
            "type", v_str("`$STRING`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("output_status"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(2,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/merchantportalws/batch/registerAdditionalTerminal/status/{id}"),
                "segments", clist(5,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "lit", v_str("registerAdditionalTerminal")),
                  cmap(1,
                    "lit", v_str("status")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("authorization"),
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(5,
                  v_str("merchantportalws"),
                  v_str("batch"),
                  v_str("registerAdditionalTerminal"),
                  v_str("status"),
                  v_str("{id}")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "output_update_product", cmap(4,
        "fields", clist(13,
          cmap(3,
            "name", v_str("allowMultipleOrders"),
            "short", v_str("An attribute to indicate if multiple orders are allowed"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("appFormName"),
            "short", v_str("The name of the application form"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("contractNeeded"),
            "short", v_str("An attribute to indicate if a contract is needed"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("credentialsNeeded"),
            "short", v_str("An attribute to indicate if credentials are needed"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("descriptionKey"),
            "short", v_str("The description of the product"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("nameKey"),
            "short", v_str("The key of the product name"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("prescreeningAllowed"),
            "short", v_str("An attribute to indicate if prescreening is allowed"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("productName"),
            "short", v_str("The name of the product"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("productStatus"),
            "short", v_str("The status of the product"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("productUUID"),
            "req", v_bool(true),
            "short", v_str("The UUID of the product to update"),
            "type", v_str("`$STRING`")),
          cmap(5,
            "format", v_str("int32"),
            "name", v_str("responseCode"),
            "req", v_bool(true),
            "short", v_str("Response code."),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("responseMessage"),
            "req", v_bool(true),
            "short", v_str("Response message."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("vendorName"),
            "short", v_str("The name of the vendor"),
            "type", v_str("`$STRING`"))),
        "name", v_str("output_update_product"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "header", clist(1,
                    cmap(5,
                      "kind", v_str("header"),
                      "name", v_str("authorization"),
                      "orig", v_str("authorization"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/merchantportalws/updateProduct"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("merchantportalws")),
                  cmap(1,
                    "lit", v_str("updateProduct"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("authorization"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("merchantportalws"),
                  v_str("updateProduct")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_audit_new(void);
Feature* feature_clienttrack_new(void);
Feature* feature_idempotency_new(void);
Feature* feature_log_new(void);
Feature* feature_metrics_new(void);
Feature* feature_paging_new(void);
Feature* feature_ratelimit_new(void);
Feature* feature_retry_new(void);
Feature* feature_telemetry_new(void);
Feature* feature_test_new(void);
Feature* feature_timeout_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "audit") == 0) return feature_audit_new();
  if (strcmp(name, "clienttrack") == 0) return feature_clienttrack_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "log") == 0) return feature_log_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "telemetry") == 0) return feature_telemetry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}


void** feature_plugins(const char* name, size_t* n) {
  (void)name;
  *n = 0;
  return NULL;
}
