

import Path from 'node:path'
import * as Fs from 'node:fs'

import { test, describe, afterEach } from 'node:test'
import assert from 'node:assert'
import { createLiveTransport } from '../../live-runner'
import { runLiveEntity } from '../../live-entity'


import { BluefinTecsMerchantPortalSDK, BaseFeature, stdutil } from '../../..'

import {
  envOverride,
  liveClientOptions,
  liveDelay,
  loadEnvLocal,
  makeCtrl,
  makeMatch,
  makeReqdata,
  makeStepData,
  makeValid,
  maybeSkipControl,
} from '../../utility'


// AFTER the imports on purpose: TypeScript hoists `import` above any
// statement in the emitted CommonJS, so a loader placed above them would
// run only after every imported module had already been evaluated - and
// anything reading process.env at module scope would miss these values.
loadEnvLocal(__dirname + '/../../../.env.local')


describe('OutputDetailEntity', async () => {

  // Per-test live pacing. Delay is read from sdk-test-control.json's
  // `test.live.delayMs`; only sleeps when BLUEFIN_TECS_MERCHANT_PORTAL_TEST_LIVE=TRUE.
  afterEach(liveDelay('BLUEFIN_TECS_MERCHANT_PORTAL_TEST_LIVE'))

  test('instance', async () => {
    const testsdk = BluefinTecsMerchantPortalSDK.test()
    const ent = testsdk.OutputDetail()
    assert(null != ent)
  })


  test('basic', async (t) => {

    const live = 'TRUE' === process.env.BLUEFIN_TECS_MERCHANT_PORTAL_TEST_LIVE
    for (const op of ['load']) {
      if (!live && maybeSkipControl(t, 'entityOp', 'output_detail.' + op, live)) return
    }

    
    const setup = basicSetup()
    if (setup.live) {
      return runLiveEntity(setup, {"active":true,"alias":{"field":{}},"fields":[{"active":true,"name":"batch","req":false,"type":"`$OBJECT`","index$":0},{"active":true,"name":"id","req":false,"type":"`$STRING`","index$":1},{"active":true,"name":"lines","req":false,"type":"`$OBJECT`","index$":2},{"active":true,"name":"progress","req":false,"type":"`$OBJECT`","index$":3}],"id":{"field":"id","name":"id"},"name":"output_detail","op":{"load":{"input":"data","name":"load","points":[{"active":true,"args":{"header":[{"active":true,"kind":"header","name":"authorization","orig":"authorization","reqd":true,"type":"`$STRING`"}],"params":[{"active":true,"kind":"param","name":"id","orig":"id","reqd":true,"type":"`$STRING`","index$":0}]},"contract":{"id":"GET /merchantportalws/batch/registerAdditionalTerminal/details/{id}","json":"{\"operationId\":\"detailsUsingGET\",\"parameters\":[{\"description\":\"Authorization\",\"in\":\"header\",\"name\":\"Authorization\",\"required\":true,\"schema\":{\"type\":\"string\"}},{\"description\":\"id\",\"in\":\"path\",\"name\":\"id\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"protocol\":\"http\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"details\":{\"properties\":{\"batch\":{\"properties\":{\"id\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"owner\":{\"type\":\"string\"},\"status\":{\"enum\":[\"COMPLETED_SUCCESSFULLY\",\"COMPLETED_WITH_ERRORS\",\"RUNNING\",\"STOPPED\"],\"type\":\"string\"},\"timestamp\":{\"type\":\"string\"}},\"title\":\"Batch\",\"type\":\"object\"},\"lines\":{\"additionalProperties\":{\"properties\":{\"data\":{\"properties\":{\"value\":{\"type\":\"string\"}},\"title\":\"Data\",\"type\":\"object\"},\"flow\":{\"properties\":{\"input\":{\"properties\":{\"additional_data\":{\"additionalProperties\":{\"type\":\"string\"},\"description\":\"Arbitrary merchant specific data related to register terminal steps.\",\"example\":{\"firstname\":\"John\",\"surname\":\"Doe\",\"type\":\"tx-300\",\"version\":\"v1.2.3\"},\"type\":\"object\"},\"currency\":{\"description\":\"Transaction currency (Has to be in \\\"ISO 4217\\\" format).\",\"example\":\"EUR\",\"type\":\"string\"},\"packageorderuuid\":{\"description\":\"Identifier of registered merchant in TECS system, provided by TECS in \\\"Merchant and terminal registration\\\" call.\",\"example\":\"dccb9a6a-b02c-46e3-aef3-a28f0b7bf993\",\"type\":\"string\"},\"password\":{\"description\":\"Merchant password for MPOS (In case if not provided, will be generated by TECS and provided in response parameters of the call).\",\"example\":\"testpassword\",\"type\":\"string\"},\"productid\":{\"description\":\"Identifier of the product for which terminal registration has to be performed.\",\"example\":\"d8af7e4f-a04f-42ea-91ac-bed20c5eebfe\",\"type\":\"string\"},\"terminal_country_code\":{\"description\":\"Terminal country code (Has to be in \\\"ISO-3166 ALPHA-3\\\" format).\",\"example\":\"SVK\",\"type\":\"string\"},\"terminal_language_code\":{\"description\":\"Terminal language code (Has to be in \\\"ISO 639-1\\\" format).\",\"example\":\"EN\",\"type\":\"string\"},\"terminal_location\":{\"description\":\"Terminal location.\",\"example\":\"Palisady 12 BA\",\"type\":\"string\"},\"terminal_serial_number\":{\"description\":\"Terminal serial number.\",\"example\":\"325-320-924\",\"type\":\"string\"},\"terminalid_acquirer\":{\"description\":\"A terminal ID set by acquirer\",\"example\":66000001,\"type\":\"string\"},\"user_email\":{\"description\":\"Email address of user, which acts in behalf of the merchant.\",\"example\":\"testemail@tecs.at\",\"type\":\"string\"},\"user_phone_number\":{\"description\":\"Phone number of user, which acts in behalf of the merchant (Has to be in international format: + country code + phone number. Example: +421910711234).\",\"example\":\"+421910876567\",\"type\":\"string\"},\"username\":{\"description\":\"Merchant username for MPOS (In case if not provided, will be generated by TECS and provided in response parameters of the call).\",\"example\":\"testuser\",\"type\":\"string\"}},\"required\":[\"currency\",\"packageorderuuid\",\"terminal_country_code\",\"terminal_language_code\",\"terminal_location\",\"terminal_serial_number\"],\"title\":\"FlowInput\",\"type\":\"object\"},\"output\":{\"properties\":{\"password\":{\"description\":\"TECS generated merchant password in case if not provided in request.\",\"example\":\"testpassword\",\"type\":\"string\"},\"responseCode\":{\"description\":\"Response code (0 = OK, otherwise an error code).\",\"example\":0,\"format\":\"int32\",\"type\":\"integer\"},\"responseMessage\":{\"description\":\"Human readable response code representation.\",\"example\":\"OK\",\"type\":\"string\"},\"terminalid\":{\"description\":\"TECS terminalid given by TECS processing engine.\",\"example\":88091104,\"format\":\"int32\",\"type\":\"integer\"},\"username\":{\"description\":\"TECS generated merchant username in case if not provided in request.\",\"example\":\"testuser\",\"type\":\"string\"}},\"required\":[\"responseCode\",\"responseMessage\"],\"title\":\"FlowOutput\",\"type\":\"object\"}},\"title\":\"Flow\",\"type\":\"object\"}},\"title\":\"Line\",\"type\":\"object\"},\"type\":\"object\"},\"progress\":{\"properties\":{\"line\":{\"type\":\"string\"},\"percentage\":{\"format\":\"int32\",\"type\":\"integer\"}},\"title\":\"Progress\",\"type\":\"object\"}},\"title\":\"Details\",\"type\":\"object\"},\"responseCode\":{\"description\":\"Response code. For success state 0. For failure state lower than 0.\",\"example\":0,\"format\":\"int32\",\"type\":\"integer\"},\"responseMessage\":{\"description\":\"Response message. For success state OK. For failure state description of the cause.\",\"example\":\"OK\",\"type\":\"string\"}},\"required\":[\"responseCode\",\"responseMessage\"],\"title\":\"OutputDetails\",\"type\":\"object\"}}},\"description\":\"OK\"}},\"securitySource\":\"unspecified\"}","source":"openapi3","version":1},"kind":"http","method":"GET","orig":"/merchantportalws/batch/registerAdditionalTerminal/details/{id}","segments":[{"lit":"merchantportalws"},{"lit":"batch"},{"lit":"registerAdditionalTerminal"},{"lit":"details"},{"var":"id"}],"select":{"exist":["authorization","id"]},"transform":{"req":"`reqdata`","res":"`body.details`"},"index$":0}],"key$":"load"}},"relations":{"ancestors":[]},"key$":"output_detail","name__orig":"output_detail","Name":"OutputDetail","name_":"output_detail","name-":"output-detail","NAME":"OUTPUT_DETAIL","index$":11}, {"active":true,"entity":"output_detail","key$":"BasicOutputDetailFlow","kind":"basic","name":"BasicOutputDetailFlow","param":{},"step":[{"active":true,"data":{},"input":{"ref":"output_detail_ref01","srcdatavar":"output_detail_ref01_data","suffix":"_dt0"},"match":{"id":"output_detail01"},"op":"load","spec":[],"valid":[{"apply":"TextFieldMark","def":{"mark":"Mark01-output_detail_ref01"}}],"index$":0}]}, 'OutputDetail')
    }
    const client = setup.client
    const struct = setup.struct

    const isempty = struct.isempty
    const select = struct.select

    let output_detail_ref01_data = Object.values(setup.data.existing.output_detail)[0] as any

    // LOAD
    const output_detail_ref01_ent = client.OutputDetail()
    const output_detail_ref01_match_dt0: any = {}
    output_detail_ref01_match_dt0.id = output_detail_ref01_data.id
    const output_detail_ref01_data_dt0 = (await output_detail_ref01_ent.load(output_detail_ref01_match_dt0)).data()
    assert(output_detail_ref01_data_dt0.id === output_detail_ref01_data.id)


  })
})



function basicSetup(extra?: any) {
  // TODO: fix test def options
  const options: any = {} // null

  // TODO: needs test utility to resolve path
  const entityDataFile =
    Path.resolve(__dirname, 
      '../../../../.sdk/test/entity/output_detail/OutputDetailTestData.json')

  // TODO: file ready util needed?
  const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8')

  // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
  const entityData = JSON.parse(entityDataSource)

  options.entity = entityData.existing

  let client = BluefinTecsMerchantPortalSDK.test(options, extra)
  const struct = client.utility().struct
  const merge = struct.merge
  const transform = struct.transform

  let idmap = transform(
    ['output_detail01','output_detail02','output_detail03'],
    {
      '`$PACK`': ['', {
        '`$KEY`': '`$COPY`',
        '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
      }]
    })

  const env = envOverride({
    'BLUEFIN_TECS_MERCHANT_PORTAL_TEST_OUTPUT_DETAIL_ENTID': idmap,
    'BLUEFIN_TECS_MERCHANT_PORTAL_TEST_LIVE': 'FALSE',
    'BLUEFIN_TECS_MERCHANT_PORTAL_TEST_EXPLAIN': 'FALSE',
  })

  idmap = env['BLUEFIN_TECS_MERCHANT_PORTAL_TEST_OUTPUT_DETAIL_ENTID']

  const live = 'TRUE' === env.BLUEFIN_TECS_MERCHANT_PORTAL_TEST_LIVE

  const transport = createLiveTransport()
  if (live) {
    const rawIds = process.env['BLUEFIN_TECS_MERCHANT_PORTAL_TEST_OUTPUT_DETAIL_ENTID']
    idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {}
    if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
      throw new Error('Live ENTID must be a JSON object')
    }
    client = new BluefinTecsMerchantPortalSDK(merge([
      // FIRST, so the generated fields below win: sdk-test-control.json's
      // test.client.options adds to the live client, it does not redirect it.
      liveClientOptions(),
      {
      },
      // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when the
      // last entry is undefined, and basicSetup is normally called with no
      // argument at all - so a bare 'extra' silently discarded the apikey
      // and server values above and handed the SDK undefined. Harmless
      // while there was nothing in that object; not harmless now.
      extra || {},
      { system: { fetch: transport.fetch } }
    ]))
  }

  const setup = {
    idmap,
    env,
    options,
    client,
    struct,
    data: entityData,
    explain: 'TRUE' === env.BLUEFIN_TECS_MERCHANT_PORTAL_TEST_EXPLAIN,
    live,
    transport,
    now: Date.now(),
  }

  return setup
}
  
