package voxgig.bluefintecsmerchantportalsdk.core

import voxgig.bluefintecsmerchantportalsdk.utility.Json

/** Static SDK configuration and by-name feature construction. */
@Suppress("UNCHECKED_CAST")
object Config {

  fun makeConfig(): MutableMap<String, Any?> {
    return Json.parse(configJson()) as MutableMap<String, Any?>
  }

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // 'by lazy' defaults to LazyThreadSafetyMode.SYNCHRONIZED, so concurrent
  // first calls build it exactly once.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  private val sharedConfigVal: MutableMap<String, Any?> by lazy { makeConfig() }

  fun sharedConfig(): MutableMap<String, Any?> = sharedConfigVal

  fun makeFeature(name: String): Feature {
    return when (name) {
      "test" -> voxgig.bluefintecsmerchantportalsdk.feature.TestFeature()
      else -> voxgig.bluefintecsmerchantportalsdk.feature.BaseFeature()
    }
  }

  private fun configJson(): String {
    val b = StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinTecsMerchantPortal\",")
    b.append("  \"slug\": \"bluefin-tecs-merchant-portal\",")
    b.append("  \"version\": \"0.1.1\",")
    b.append("  \"target\": \"kotlin\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://test.tecs.at\",")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"merchant_portal_api_controller\": {},")
    b.append("   \"merchant_portal_common_controller\": {},")
    b.append("   \"merchant_portal_pam_contract_controller\": {},")
    b.append("   \"merchant_portal_pam_document_controller\": {},")
    b.append("   \"merchant_portal_pam_form_controller\": {},")
    b.append("   \"merchant_portal_pam_mandator_controller\": {},")
    b.append("   \"merchant_portal_pam_merchant_controller\": {},")
    b.append("   \"merchant_portal_pam_package_controller\": {},")
    b.append("   \"merchant_portal_pam_product_controller\": {},")
    b.append("   \"output_add_product\": {},")
    b.append("   \"output_create_product\": {},")
    b.append("   \"output_detail\": {},")
    b.append("   \"output_list\": {},")
    b.append("   \"output_message\": {},")
    b.append("   \"output_move_tid\": {},")
    b.append("   \"output_remove_product\": {},")
    b.append("   \"output_start\": {},")
    b.append("   \"output_status\": {},")
    b.append("   \"output_update_product\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"merchant_portal_api_controller\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"account_number\",")
    b.append("     \"short\": \"Account number provided by the acquirer.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"additional_data\",")
    b.append("     \"short\": \"Arbitrary merchant-specific data related to terminal registration.\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"business_reg_number\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Merchant business registration number as stated in the company registry.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"city\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Merchant's address: city.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"corporateuuid\",")
    b.append("     \"short\": \"Unique identifier for the corporate entity (UUID format).\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"country\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Merchant's address: country (must be in 'ISO-3166 ALPHA-3' format).\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"currency\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Transaction currency (must be in \\\"ISO 4217\\\" format).\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"merchant_category_code\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Merchant category code as defined by the payment network.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"merchant_email\",")
    b.append("     \"short\": \"Merchant's email address for receiving notifications.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"merchant_name\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The officially incorporated company name of the merchant.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"merchant_phone_number\",")
    b.append("     \"short\": \"Merchant's phone number for notifications.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageid\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Identifier of the package in the TECS processing engine provided by TECS.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageorderuuid\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Identifier of the registered merchant in the TECS system, provided in the response of the registerNewMerchant call.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"password\",")
    b.append("     \"short\": \"Merchant password for MPOS.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productid\",")
    b.append("     \"short\": \"Identifier of the product for which terminal registration is to be performed.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productid_acquirer\",")
    b.append("     \"short\": \"Identifier of the product for which acquiring is enabled.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reason_deactivation\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Reason for terminal deactivation.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reason_reactivation\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Reason for terminal reactivation.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sorting_code\",")
    b.append("     \"short\": \"Sorting code provided by the acquirer.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"state\",")
    b.append("     \"short\": \"Merchant's address: state.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"street\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Merchant's address: street and house number.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminal_country_code\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Terminal country code (must be in 'ISO-3166 ALPHA-3' format).\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminal_language_code\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Terminal language code (must be in 'ISO 639-1' format).\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminal_location\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Physical or logical location of the terminal.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminal_serial_number\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Terminal serial number.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminalid\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"TECS terminalid given by Tecs processing engine.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminalid_acquirer\",")
    b.append("     \"short\": \"Terminal ID as set by the acquirer (optional).\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"user_email\",")
    b.append("     \"short\": \"Email address of the user acting on behalf of the merchant.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"user_phone_number\",")
    b.append("     \"short\": \"Phone number of the user acting on behalf of the merchant.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"username\",")
    b.append("     \"short\": \"Merchant username for MPOS.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"vu_nummer\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Merchant contract number with the acquirer.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"web_shop_url\",")
    b.append("     \"short\": \"URL of the merchant's web shop.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"zipcode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Merchant's address: postal code.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"merchant_portal_api_controller\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/deactivateTerminal\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"deactivateTerminal\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/reactivateTerminal\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"reactivateTerminal\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/registerAdditionalTerminal\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"registerAdditionalTerminal\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/registerNewMerchant\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"registerNewMerchant\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"merchant_portal_common_controller\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"merchant_portal_common_controller\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/merchantportalws/logDeveloperInfo\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"logDeveloperInfo\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/merchantportalws/version\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"version\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"merchant_portal_pam_contract_controller\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"language\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productOrderUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"merchant_portal_pam_contract_controller\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/generateContract\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"generateContract\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/uploadContract\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"uploadContract\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"merchant_portal_pam_document_controller\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"appFormFieldDescUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageOrderUUID\",")
    b.append("     \"short\": \"UUID of the package order.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productOrderUUID\",")
    b.append("     \"short\": \"UUID of the product order.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"merchant_portal_pam_document_controller\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/documentsList\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"documentsList\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/downloadDocument\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"downloadDocument\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"merchant_portal_pam_form_controller\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"appFormFieldsDescUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"filter\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"language\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageOrder\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageOrderUUID\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"UUID of the package order.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageUUID\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productOrderUUID\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"short\": \"UUID of the product order.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productOrders\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reasonOfReopening\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"merchant_portal_pam_form_controller\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/applicationForm\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"applicationForm\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/packageForm\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"packageForm\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/reopenForm\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"reopenForm\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/secretKey\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"secretKey\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/submitForm\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"submitForm\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/submitValues\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"submitValues\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"merchant_portal_pam_mandator_controller\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"clientSecret\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"mandatorName\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"notificationEmail\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"merchant_portal_pam_mandator_controller\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/createMandatorConfig\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"createMandatorConfig\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/introduceMandatorPackage\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"introduceMandatorPackage\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/selfRegistrationLink\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"selfRegistrationLink\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"merchant_portal_pam_merchant_controller\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"additional_data\",")
    b.append("     \"short\": \"Optional additional merchant-specific data related to enabling acquiring.\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"businessRegistrationNumber\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"city\",")
    b.append("     \"short\": \"City where the merchant is located.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"companyName\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"corporateUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Unique identifier for the corporate entity.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"country\",")
    b.append("     \"short\": \"Country where the merchant is located.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"currency\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Transaction currency in ISO 4217 format.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"email\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"language\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"login\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"mandator\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Mandator name assigned by TECS.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"merchantContractNumber\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Unique identifier for the merchant within a specific system.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"merchantName\",")
    b.append("     \"short\": \"Name of the merchant.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"merchant_category_code\",")
    b.append("     \"short\": \"Merchant Category Code (MCC) describing the merchant’s type of business.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageUUID\",")
    b.append("     \"short\": \"UUID of the package.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageorderuuid\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Unique identifier for the registered merchant in the TECS system.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"phoneNumber\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"postalCode\",")
    b.append("     \"short\": \"Postal or ZIP code of the merchant’s location.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productid_acquirer\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Identifier of the product for which acquiring is to be enabled.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"region\",")
    b.append("     \"short\": \"State or province where the merchant is located.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"registrationNumber\",")
    b.append("     \"short\": \"Business registration number.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"signature\",")
    b.append("     \"short\": \"Signature value = saltAsHex-hashAsHex.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"street\",")
    b.append("     \"short\": \"Street address of the merchant.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminalIds\",")
    b.append("     \"short\": \"Optional list of terminal IDs for which acquiring should be activated.\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminalid_acquirer\",")
    b.append("     \"short\": \"Optional terminal ID provided by the acquirer.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"vu_nummer\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Merchant contract number with the acquirer.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"merchant_portal_pam_merchant_controller\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/contractNumber\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"contractNumber\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/registerAdditionalAcquiring\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"registerAdditionalAcquiring\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/updateMerchant\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"updateMerchant\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/registerMerchant\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"registerMerchant\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"merchant_portal_pam_package_controller\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"corporateUUID\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"country\",")
    b.append("     \"short\": \"Country associated with the package.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"descriptionKey\",")
    b.append("     \"short\": \"Key for the description of the package.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"filter\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"language\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"nameKey\",")
    b.append("     \"short\": \"Key for the name of the package.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageStatus\",")
    b.append("     \"short\": \"Status of the package.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Unique identifier for the package.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"merchant_portal_pam_package_controller\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/availablePackages\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"availablePackages\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/orderPackage\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"orderPackage\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/orderedPackages\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"orderedPackages\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/packageTemplates\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"packageTemplates\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/updatePackageData\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"updatePackageData\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"merchant_portal_pam_product_controller\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"consumerUUID\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"filter\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"language\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"merchantID\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"packageOrderUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productOrderUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"reason_decline\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Reason for product decline.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"merchant_portal_pam_product_controller\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/approveProduct\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"approveProduct\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/declineProduct\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"declineProduct\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/orderAdditionalProduct\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"orderAdditionalProduct\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/productsList\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"productsList\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_add_product\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"packageUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Unique identifier for the package.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productUUIDs\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The list of unique identifiers of the products.\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response code.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_add_product\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/addProductsToPackage\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"addProductsToPackage\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_create_product\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"acquirerId\",")
    b.append("     \"short\": \"Unique identifier for the acquirer.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"allowMultipleOrders\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Indication whether multiple orders are allowed or not.\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"appFormTemplateName\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Name of the application form template.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"contractNeeded\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Indication whether contract is needed or not.\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"credentialsNeeded\",")
    b.append("     \"short\": \"Indication whether credentials are needed or not.\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"descriptionKey\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Key indicator for product description.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"nameKey\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Key indicator for product name.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"prescreeningAllowed\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Indication whether prescreening is allowed or not.\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productName\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Name of the product.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response code.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"terminalTemplateName\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Name of the terminal template.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"vendorName\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Name of the vendor.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"xmlTemplateFile\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"A string value containing the XML template file encoded in Base64.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_create_product\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/createNewProduct\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"createNewProduct\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_detail\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"batch\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"lines\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"progress\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_detail\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ],")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/merchantportalws/batch/registerAdditionalTerminal/details/{id}\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"batch\",")
    b.append("        \"registerAdditionalTerminal\",")
    b.append("        \"details\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\",")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body.details`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_list\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"items\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"pagination\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"type\": \"`\$OBJECT`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response code.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sorting\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_list\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/batch/registerAdditionalTerminal/list\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"batch\",")
    b.append("        \"registerAdditionalTerminal\",")
    b.append("        \"list\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_message\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response code.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_message\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ],")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/merchantportalws/batch/registerAdditionalTerminal/restart/{id}\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"batch\",")
    b.append("        \"registerAdditionalTerminal\",")
    b.append("        \"restart\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\",")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ],")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/merchantportalws/batch/registerAdditionalTerminal/stop/{id}\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"batch\",")
    b.append("        \"registerAdditionalTerminal\",")
    b.append("        \"stop\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\",")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_move_tid\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"productOrderUUIDs\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response code.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"targetPackageOrderUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"targetProductOrderUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_move_tid\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/moveTid\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"moveTid\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_remove_product\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"packageUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Unique identifier for the package.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productUUIDs\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"List of product unique identifiers.\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response code.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_remove_product\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/removeProductsFromPackage\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"removeProductsFromPackage\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_start\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"id\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response code.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_start\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/batch/registerAdditionalTerminal/start\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"batch\",")
    b.append("        \"registerAdditionalTerminal\",")
    b.append("        \"start\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_status\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"percentage\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response code.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"status\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_status\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ],")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/merchantportalws/batch/registerAdditionalTerminal/status/{id}\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"batch\",")
    b.append("        \"registerAdditionalTerminal\",")
    b.append("        \"status\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\",")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"output_update_product\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"allowMultipleOrders\",")
    b.append("     \"short\": \"An attribute to indicate if multiple orders are allowed\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"appFormName\",")
    b.append("     \"short\": \"The name of the application form\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"contractNeeded\",")
    b.append("     \"short\": \"An attribute to indicate if a contract is needed\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"credentialsNeeded\",")
    b.append("     \"short\": \"An attribute to indicate if credentials are needed\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"descriptionKey\",")
    b.append("     \"short\": \"The description of the product\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"nameKey\",")
    b.append("     \"short\": \"The key of the product name\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"prescreeningAllowed\",")
    b.append("     \"short\": \"An attribute to indicate if prescreening is allowed\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productName\",")
    b.append("     \"short\": \"The name of the product\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productStatus\",")
    b.append("     \"short\": \"The status of the product\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"productUUID\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The UUID of the product to update\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseCode\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response code.\",")
    b.append("     \"type\": \"`\$INTEGER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseMessage\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Response message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"vendorName\",")
    b.append("     \"short\": \"The name of the vendor\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"output_update_product\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"header\": [")
    b.append("         {")
    b.append("          \"kind\": \"header\",")
    b.append("          \"name\": \"authorization\",")
    b.append("          \"orig\": \"authorization\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/merchantportalws/updateProduct\",")
    b.append("       \"parts\": [")
    b.append("        \"merchantportalws\",")
    b.append("        \"updateProduct\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"authorization\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    return b.toString()
  }
}
