// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/bluefin-tecs-merchant-portal-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"merchant_portal_api_controller | merchant_portal_common_controller | merchant_portal_pam_contract_controller | merchant_portal_pam_document_controller | merchant_portal_pam_form_controller | merchant_portal_pam_mandator_controller | merchant_portal_pam_merchant_controller | merchant_portal_pam_package_controller | merchant_portal_pam_product_controller | output_add_product | output_create_product | output_detail | output_list | output_message | output_move_tid | output_remove_product | output_start | output_status | output_update_product"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.BluefinTecsMerchantPortalSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-tecs-merchant-portal_list",
		Description: "List records from BluefinTecsMerchantPortal. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-tecs-merchant-portal_load",
		Description: "Load a single record from BluefinTecsMerchantPortal. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.BluefinTecsMerchantPortalSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.BluefinTecsMerchantPortalSDK, name string) (sdk.BluefinTecsMerchantPortalEntity, error) {
	switch strings.ToLower(name) {
	case "merchant_portal_api_controller":
		return client.MerchantPortalApiController(nil), nil
	case "merchant_portal_common_controller":
		return client.MerchantPortalCommonController(nil), nil
	case "merchant_portal_pam_contract_controller":
		return client.MerchantPortalPamContractController(nil), nil
	case "merchant_portal_pam_document_controller":
		return client.MerchantPortalPamDocumentController(nil), nil
	case "merchant_portal_pam_form_controller":
		return client.MerchantPortalPamFormController(nil), nil
	case "merchant_portal_pam_mandator_controller":
		return client.MerchantPortalPamMandatorController(nil), nil
	case "merchant_portal_pam_merchant_controller":
		return client.MerchantPortalPamMerchantController(nil), nil
	case "merchant_portal_pam_package_controller":
		return client.MerchantPortalPamPackageController(nil), nil
	case "merchant_portal_pam_product_controller":
		return client.MerchantPortalPamProductController(nil), nil
	case "output_add_product":
		return client.OutputAddProduct(nil), nil
	case "output_create_product":
		return client.OutputCreateProduct(nil), nil
	case "output_detail":
		return client.OutputDetail(nil), nil
	case "output_list":
		return client.OutputList(nil), nil
	case "output_message":
		return client.OutputMessage(nil), nil
	case "output_move_tid":
		return client.OutputMoveTid(nil), nil
	case "output_remove_product":
		return client.OutputRemoveProduct(nil), nil
	case "output_start":
		return client.OutputStart(nil), nil
	case "output_status":
		return client.OutputStatus(nil), nil
	case "output_update_product":
		return client.OutputUpdateProduct(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
