(* BluefinTecsMerchantPortal SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs

(* MerchantPortalApiController entity bound to a client:  merchant_portal_api_controller client entopts *)
let merchant_portal_api_controller (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_api_controller.make client entopts

(* MerchantPortalCommonController entity bound to a client:  merchant_portal_common_controller client entopts *)
let merchant_portal_common_controller (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_common_controller.make client entopts

(* MerchantPortalPamContractController entity bound to a client:  merchant_portal_pam_contract_controller client entopts *)
let merchant_portal_pam_contract_controller (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_pam_contract_controller.make client entopts

(* MerchantPortalPamDocumentController entity bound to a client:  merchant_portal_pam_document_controller client entopts *)
let merchant_portal_pam_document_controller (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_pam_document_controller.make client entopts

(* MerchantPortalPamFormController entity bound to a client:  merchant_portal_pam_form_controller client entopts *)
let merchant_portal_pam_form_controller (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_pam_form_controller.make client entopts

(* MerchantPortalPamMandatorController entity bound to a client:  merchant_portal_pam_mandator_controller client entopts *)
let merchant_portal_pam_mandator_controller (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_pam_mandator_controller.make client entopts

(* MerchantPortalPamMerchantController entity bound to a client:  merchant_portal_pam_merchant_controller client entopts *)
let merchant_portal_pam_merchant_controller (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_pam_merchant_controller.make client entopts

(* MerchantPortalPamPackageController entity bound to a client:  merchant_portal_pam_package_controller client entopts *)
let merchant_portal_pam_package_controller (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_pam_package_controller.make client entopts

(* MerchantPortalPamProductController entity bound to a client:  merchant_portal_pam_product_controller client entopts *)
let merchant_portal_pam_product_controller (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_merchant_portal_pam_product_controller.make client entopts

(* OutputAddProduct entity bound to a client:  output_add_product client entopts *)
let output_add_product (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_add_product.make client entopts

(* OutputCreateProduct entity bound to a client:  output_create_product client entopts *)
let output_create_product (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_create_product.make client entopts

(* OutputDetail entity bound to a client:  output_detail client entopts *)
let output_detail (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_detail.make client entopts

(* OutputList entity bound to a client:  output_list client entopts *)
let output_list (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_list.make client entopts

(* OutputMessage entity bound to a client:  output_message client entopts *)
let output_message (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_message.make client entopts

(* OutputMoveTid entity bound to a client:  output_move_tid client entopts *)
let output_move_tid (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_move_tid.make client entopts

(* OutputRemoveProduct entity bound to a client:  output_remove_product client entopts *)
let output_remove_product (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_remove_product.make client entopts

(* OutputStart entity bound to a client:  output_start client entopts *)
let output_start (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_start.make client entopts

(* OutputStatus entity bound to a client:  output_status client entopts *)
let output_status (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_status.make client entopts

(* OutputUpdateProduct entity bound to a client:  output_update_product client entopts *)
let output_update_product (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_output_update_product.make client entopts
