-- BluefinTecsMerchantPortal SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
  , merchant_portal_api_controller
  , merchant_portal_common_controller
  , merchant_portal_pam_contract_controller
  , merchant_portal_pam_document_controller
  , merchant_portal_pam_form_controller
  , merchant_portal_pam_mandator_controller
  , merchant_portal_pam_merchant_controller
  , merchant_portal_pam_package_controller
  , merchant_portal_pam_product_controller
  , output_add_product
  , output_create_product
  , output_detail
  , output_list
  , output_message
  , output_move_tid
  , output_remove_product
  , output_start
  , output_status
  , output_update_product
  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

-- | The MerchantPortalApiController entity bound to this client.
merchant_portal_api_controller :: Client -> Value -> IO Entity
merchant_portal_api_controller client entopts = F.makeEntity client "merchant_portal_api_controller" entopts

-- | The MerchantPortalCommonController entity bound to this client.
merchant_portal_common_controller :: Client -> Value -> IO Entity
merchant_portal_common_controller client entopts = F.makeEntity client "merchant_portal_common_controller" entopts

-- | The MerchantPortalPamContractController entity bound to this client.
merchant_portal_pam_contract_controller :: Client -> Value -> IO Entity
merchant_portal_pam_contract_controller client entopts = F.makeEntity client "merchant_portal_pam_contract_controller" entopts

-- | The MerchantPortalPamDocumentController entity bound to this client.
merchant_portal_pam_document_controller :: Client -> Value -> IO Entity
merchant_portal_pam_document_controller client entopts = F.makeEntity client "merchant_portal_pam_document_controller" entopts

-- | The MerchantPortalPamFormController entity bound to this client.
merchant_portal_pam_form_controller :: Client -> Value -> IO Entity
merchant_portal_pam_form_controller client entopts = F.makeEntity client "merchant_portal_pam_form_controller" entopts

-- | The MerchantPortalPamMandatorController entity bound to this client.
merchant_portal_pam_mandator_controller :: Client -> Value -> IO Entity
merchant_portal_pam_mandator_controller client entopts = F.makeEntity client "merchant_portal_pam_mandator_controller" entopts

-- | The MerchantPortalPamMerchantController entity bound to this client.
merchant_portal_pam_merchant_controller :: Client -> Value -> IO Entity
merchant_portal_pam_merchant_controller client entopts = F.makeEntity client "merchant_portal_pam_merchant_controller" entopts

-- | The MerchantPortalPamPackageController entity bound to this client.
merchant_portal_pam_package_controller :: Client -> Value -> IO Entity
merchant_portal_pam_package_controller client entopts = F.makeEntity client "merchant_portal_pam_package_controller" entopts

-- | The MerchantPortalPamProductController entity bound to this client.
merchant_portal_pam_product_controller :: Client -> Value -> IO Entity
merchant_portal_pam_product_controller client entopts = F.makeEntity client "merchant_portal_pam_product_controller" entopts

-- | The OutputAddProduct entity bound to this client.
output_add_product :: Client -> Value -> IO Entity
output_add_product client entopts = F.makeEntity client "output_add_product" entopts

-- | The OutputCreateProduct entity bound to this client.
output_create_product :: Client -> Value -> IO Entity
output_create_product client entopts = F.makeEntity client "output_create_product" entopts

-- | The OutputDetail entity bound to this client.
output_detail :: Client -> Value -> IO Entity
output_detail client entopts = F.makeEntity client "output_detail" entopts

-- | The OutputList entity bound to this client.
output_list :: Client -> Value -> IO Entity
output_list client entopts = F.makeEntity client "output_list" entopts

-- | The OutputMessage entity bound to this client.
output_message :: Client -> Value -> IO Entity
output_message client entopts = F.makeEntity client "output_message" entopts

-- | The OutputMoveTid entity bound to this client.
output_move_tid :: Client -> Value -> IO Entity
output_move_tid client entopts = F.makeEntity client "output_move_tid" entopts

-- | The OutputRemoveProduct entity bound to this client.
output_remove_product :: Client -> Value -> IO Entity
output_remove_product client entopts = F.makeEntity client "output_remove_product" entopts

-- | The OutputStart entity bound to this client.
output_start :: Client -> Value -> IO Entity
output_start client entopts = F.makeEntity client "output_start" entopts

-- | The OutputStatus entity bound to this client.
output_status :: Client -> Value -> IO Entity
output_status client entopts = F.makeEntity client "output_status" entopts

-- | The OutputUpdateProduct entity bound to this client.
output_update_product :: Client -> Value -> IO Entity
output_update_product client entopts = F.makeEntity client "output_update_product" entopts

