-- BluefinTecsMerchantPortal SDK test runner (generated by @voxgig/sdkgen).
--
-- OFFLINE lane (always): a test-mode client seeded from the generated entity
-- test data answers operations from an in-memory store — no server needed.
-- LIVE lane (only when SDK_TEST_BASE is set): the same flow over real HTTP.

import VoxgigStruct
import SdkJson
import SdkRuntime
import SdkClient

open VoxgigStruct

initialize npass : IO.Ref Nat ← IO.mkRef 0
initialize nfail : IO.Ref Nat ← IO.mkRef 0

def pass (msg : String) : SIO Unit := do
  npass.modify (· + 1)
  IO.println s!"ok   - {msg}"

def fail (msg : String) : SIO Unit := do
  nfail.modify (· + 1)
  IO.println s!"FAIL - {msg}"

def defaultBase : String := "http://localhost:8901"

def main : IO UInt32 := do
  let liveBase ← IO.getEnv "SDK_TEST_BASE"
  let ctx ← mkCtx
  let offline : SIO Unit := do
    -- output_detail: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/output_detail/OutputDetailTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - output_detail: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "output_detail"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Output_detail.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"output_detail.load offline (id={wid})"
          else fail s!"output_detail.load offline: got {gid}, want {wid}"
)
    -- output_message: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/output_message/OutputMessageTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - output_message: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "output_message"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Output_message.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"output_message.load offline (id={wid})"
          else fail s!"output_message.load offline: got {gid}, want {wid}"
)
    -- output_status: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/output_status/OutputStatusTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - output_status: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "output_status"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Output_status.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"output_status.load offline (id={wid})"
          else fail s!"output_status.load offline: got {gid}, want {wid}"
)
  offline.run ctx
  match liveBase with
  | none => IO.println "skip - live lane (set SDK_TEST_BASE to enable)"
  | some base => do
    let live : SIO Unit := do
      let opts ← newMap #[("base", .str base)]
      let client ← Sdk.newSdk opts
      pure ()
    live.run ctx
  let p ← npass.get
  let f ← nfail.get
  IO.println ""
  IO.println s!"PASS {p}  FAIL {f}"
  if f > 0 then return 1 else return 0
