;; BluefinTecsMerchantPortal SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.merchant_portal_api_controller :as e-merchant_portal_api_controller]
            [sdk.entity.merchant_portal_common_controller :as e-merchant_portal_common_controller]
            [sdk.entity.merchant_portal_pam_contract_controller :as e-merchant_portal_pam_contract_controller]
            [sdk.entity.merchant_portal_pam_document_controller :as e-merchant_portal_pam_document_controller]
            [sdk.entity.merchant_portal_pam_form_controller :as e-merchant_portal_pam_form_controller]
            [sdk.entity.merchant_portal_pam_mandator_controller :as e-merchant_portal_pam_mandator_controller]
            [sdk.entity.merchant_portal_pam_merchant_controller :as e-merchant_portal_pam_merchant_controller]
            [sdk.entity.merchant_portal_pam_package_controller :as e-merchant_portal_pam_package_controller]
            [sdk.entity.merchant_portal_pam_product_controller :as e-merchant_portal_pam_product_controller]
            [sdk.entity.output_add_product :as e-output_add_product]
            [sdk.entity.output_create_product :as e-output_create_product]
            [sdk.entity.output_detail :as e-output_detail]
            [sdk.entity.output_list :as e-output_list]
            [sdk.entity.output_message :as e-output_message]
            [sdk.entity.output_move_tid :as e-output_move_tid]
            [sdk.entity.output_remove_product :as e-output_remove_product]
            [sdk.entity.output_start :as e-output_start]
            [sdk.entity.output_status :as e-output_status]
            [sdk.entity.output_update_product :as e-output_update_product]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def prepare client/prepare)
(def options-map client/options-map)

;; MerchantPortalApiController accessor: (merchant_portal_api_controller client data)
(defn merchant_portal_api_controller [client data] (e-merchant_portal_api_controller/make client data))

;; MerchantPortalCommonController accessor: (merchant_portal_common_controller client data)
(defn merchant_portal_common_controller [client data] (e-merchant_portal_common_controller/make client data))

;; MerchantPortalPamContractController accessor: (merchant_portal_pam_contract_controller client data)
(defn merchant_portal_pam_contract_controller [client data] (e-merchant_portal_pam_contract_controller/make client data))

;; MerchantPortalPamDocumentController accessor: (merchant_portal_pam_document_controller client data)
(defn merchant_portal_pam_document_controller [client data] (e-merchant_portal_pam_document_controller/make client data))

;; MerchantPortalPamFormController accessor: (merchant_portal_pam_form_controller client data)
(defn merchant_portal_pam_form_controller [client data] (e-merchant_portal_pam_form_controller/make client data))

;; MerchantPortalPamMandatorController accessor: (merchant_portal_pam_mandator_controller client data)
(defn merchant_portal_pam_mandator_controller [client data] (e-merchant_portal_pam_mandator_controller/make client data))

;; MerchantPortalPamMerchantController accessor: (merchant_portal_pam_merchant_controller client data)
(defn merchant_portal_pam_merchant_controller [client data] (e-merchant_portal_pam_merchant_controller/make client data))

;; MerchantPortalPamPackageController accessor: (merchant_portal_pam_package_controller client data)
(defn merchant_portal_pam_package_controller [client data] (e-merchant_portal_pam_package_controller/make client data))

;; MerchantPortalPamProductController accessor: (merchant_portal_pam_product_controller client data)
(defn merchant_portal_pam_product_controller [client data] (e-merchant_portal_pam_product_controller/make client data))

;; OutputAddProduct accessor: (output_add_product client data)
(defn output_add_product [client data] (e-output_add_product/make client data))

;; OutputCreateProduct accessor: (output_create_product client data)
(defn output_create_product [client data] (e-output_create_product/make client data))

;; OutputDetail accessor: (output_detail client data)
(defn output_detail [client data] (e-output_detail/make client data))

;; OutputList accessor: (output_list client data)
(defn output_list [client data] (e-output_list/make client data))

;; OutputMessage accessor: (output_message client data)
(defn output_message [client data] (e-output_message/make client data))

;; OutputMoveTid accessor: (output_move_tid client data)
(defn output_move_tid [client data] (e-output_move_tid/make client data))

;; OutputRemoveProduct accessor: (output_remove_product client data)
(defn output_remove_product [client data] (e-output_remove_product/make client data))

;; OutputStart accessor: (output_start client data)
(defn output_start [client data] (e-output_start/make client data))

;; OutputStatus accessor: (output_status client data)
(defn output_status [client data] (e-output_status/make client data))

;; OutputUpdateProduct accessor: (output_update_product client data)
(defn output_update_product [client data] (e-output_update_product/make client data))
