;; BluefinTecsMerchantPortal SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "merchant_portal_api_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "account_number"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "additional_data"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "business_reg_number"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "city"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "corporateuuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "country"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "merchant_category_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "merchant_email"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "merchant_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "merchant_phone_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "packageid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "packageorderuuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "password"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 14
            "name" "productid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 15
            "name" "productid_acquirer"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 16
            "name" "reason_deactivation"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 17
            "name" "reason_reactivation"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 18
            "name" "sorting_code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 19
            "name" "state"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 20
            "name" "street"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 21
            "name" "terminal_country_code"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 22
            "name" "terminal_language_code"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 23
            "name" "terminal_location"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 24
            "name" "terminal_serial_number"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 25
            "name" "terminalid"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 26
            "name" "terminalid_acquirer"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 27
            "name" "user_email"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 28
            "name" "user_phone_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 29
            "name" "username"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 30
            "name" "vu_nummer"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 31
            "name" "web_shop_url"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 32
            "name" "zipcode"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_api_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/deactivateTerminal"
                "parts" (vs/jt
                  "merchantportalws"
                  "deactivateTerminal")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/merchantportalws/reactivateTerminal"
                "parts" (vs/jt
                  "merchantportalws"
                  "reactivateTerminal")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 2
                "method" "POST"
                "orig" "/merchantportalws/registerAdditionalTerminal"
                "parts" (vs/jt
                  "merchantportalws"
                  "registerAdditionalTerminal")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 3
                "method" "POST"
                "orig" "/merchantportalws/registerNewMerchant"
                "parts" (vs/jt
                  "merchantportalws"
                  "registerNewMerchant")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_common_controller" (vs/jm
        "fields" (vs/jt)
        "name" "merchant_portal_common_controller"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "GET"
                "orig" "/merchantportalws/logDeveloperInfo"
                "parts" (vs/jt
                  "merchantportalws"
                  "logDeveloperInfo")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "GET"
                "orig" "/merchantportalws/version"
                "parts" (vs/jt
                  "merchantportalws"
                  "version")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_contract_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "language"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "product_order_uuid"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_contract_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/generateContract"
                "parts" (vs/jt
                  "merchantportalws"
                  "generateContract")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/merchantportalws/uploadContract"
                "parts" (vs/jt
                  "merchantportalws"
                  "uploadContract")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_document_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "app_form_field_desc_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "package_order_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "product_order_uuid"
            "req" false
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_document_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/documentsList"
                "parts" (vs/jt
                  "merchantportalws"
                  "documentsList")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/merchantportalws/downloadDocument"
                "parts" (vs/jt
                  "merchantportalws"
                  "downloadDocument")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_form_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "app_form_fields_desc_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "filter"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "language"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "package_order"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "package_order_uuid"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "package_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "product_order"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "product_order_uuid"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "reason_of_reopening"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_form_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/applicationForm"
                "parts" (vs/jt
                  "merchantportalws"
                  "applicationForm")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/merchantportalws/packageForm"
                "parts" (vs/jt
                  "merchantportalws"
                  "packageForm")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 2
                "method" "POST"
                "orig" "/merchantportalws/reopenForm"
                "parts" (vs/jt
                  "merchantportalws"
                  "reopenForm")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 3
                "method" "POST"
                "orig" "/merchantportalws/secretKey"
                "parts" (vs/jt
                  "merchantportalws"
                  "secretKey")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 4
                "method" "POST"
                "orig" "/merchantportalws/submitForm"
                "parts" (vs/jt
                  "merchantportalws"
                  "submitForm")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 5
                "method" "POST"
                "orig" "/merchantportalws/submitValues"
                "parts" (vs/jt
                  "merchantportalws"
                  "submitValues")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_mandator_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "client_secret"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "mandator_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "notification_email"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "package_uuid"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_mandator_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/createMandatorConfig"
                "parts" (vs/jt
                  "merchantportalws"
                  "createMandatorConfig")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/merchantportalws/introduceMandatorPackage"
                "parts" (vs/jt
                  "merchantportalws"
                  "introduceMandatorPackage")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 2
                "method" "POST"
                "orig" "/merchantportalws/selfRegistrationLink"
                "parts" (vs/jt
                  "merchantportalws"
                  "selfRegistrationLink")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_merchant_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "additional_data"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "business_registration_number"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "city"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "company_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "corporate_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "country"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "email"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "language"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "login"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "mandator"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "merchant_category_code"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "merchant_contract_number"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "merchant_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 14
            "name" "package_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 15
            "name" "packageorderuuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 16
            "name" "phone_number"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 17
            "name" "postal_code"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 18
            "name" "productid_acquirer"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 19
            "name" "region"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 20
            "name" "registration_number"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 21
            "name" "signature"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 22
            "name" "street"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 23
            "name" "terminal_id"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 24
            "name" "terminalid_acquirer"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 25
            "name" "vu_nummer"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_merchant_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/contractNumber"
                "parts" (vs/jt
                  "merchantportalws"
                  "contractNumber")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/merchantportalws/registerAdditionalAcquiring"
                "parts" (vs/jt
                  "merchantportalws"
                  "registerAdditionalAcquiring")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 2
                "method" "POST"
                "orig" "/merchantportalws/updateMerchant"
                "parts" (vs/jt
                  "merchantportalws"
                  "updateMerchant")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 3
                "method" "POST"
                "orig" "/merchantportalws/registerMerchant"
                "parts" (vs/jt
                  "merchantportalws"
                  "registerMerchant")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_package_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "consumer_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "corporate_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "country"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "description_key"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "filter"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "language"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "name_key"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "package_status"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "package_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "pagination"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "sorting"
            "req" false
            "type" "`$OBJECT`"))
        "name" "merchant_portal_pam_package_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/availablePackages"
                "parts" (vs/jt
                  "merchantportalws"
                  "availablePackages")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/merchantportalws/orderPackage"
                "parts" (vs/jt
                  "merchantportalws"
                  "orderPackage")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 2
                "method" "POST"
                "orig" "/merchantportalws/orderedPackages"
                "parts" (vs/jt
                  "merchantportalws"
                  "orderedPackages")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 3
                "method" "POST"
                "orig" "/merchantportalws/packageTemplates"
                "parts" (vs/jt
                  "merchantportalws"
                  "packageTemplates")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" false
                      "type" "`$STRING`")))
                "index$" 4
                "method" "POST"
                "orig" "/merchantportalws/updatePackageData"
                "parts" (vs/jt
                  "merchantportalws"
                  "updatePackageData")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_product_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "consumer_uuid"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "filter"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "language"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "merchant_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "package_order_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "pagination"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "product_order_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "product_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "reason_decline"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "sorting"
            "req" false
            "type" "`$OBJECT`"))
        "name" "merchant_portal_pam_product_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/approveProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "approveProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "POST"
                "orig" "/merchantportalws/declineProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "declineProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 2
                "method" "POST"
                "orig" "/merchantportalws/orderAdditionalProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "orderAdditionalProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 3
                "method" "POST"
                "orig" "/merchantportalws/productsList"
                "parts" (vs/jt
                  "merchantportalws"
                  "productsList")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_add_product" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "package_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "product_uui_d"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" true
            "type" "`$STRING`"))
        "name" "output_add_product"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/addProductsToPackage"
                "parts" (vs/jt
                  "merchantportalws"
                  "addProductsToPackage")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_create_product" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "acquirer_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "allow_multiple_order"
            "req" true
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "app_form_template_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "contract_needed"
            "req" true
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "credentials_needed"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "description_key"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "name_key"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "prescreening_allowed"
            "req" true
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "product_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "response_message"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "terminal_template_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "vendor_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "xml_template_file"
            "req" true
            "type" "`$STRING`"))
        "name" "output_create_product"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/createNewProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "createNewProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_detail" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "detail"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" true
            "type" "`$STRING`"))
        "name" "output_detail"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`"))
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/details/{id}"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "details"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "item"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "pagination"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$OBJECT`"))
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "sorting"
            "req" false
            "type" "`$OBJECT`"))
        "name" "output_list"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/list"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "list")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_message" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_message"
            "req" true
            "type" "`$STRING`"))
        "name" "output_message"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`"))
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/restart/{id}"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "restart"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`"))
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "GET"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/stop/{id}"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "stop"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_move_tid" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "product_order_uui_d"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "target_package_order_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "target_product_order_uuid"
            "req" true
            "type" "`$STRING`"))
        "name" "output_move_tid"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/moveTid"
                "parts" (vs/jt
                  "merchantportalws"
                  "moveTid")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_remove_product" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "package_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "product_uui_d"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "response_message"
            "req" true
            "type" "`$STRING`"))
        "name" "output_remove_product"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/removeProductsFromPackage"
                "parts" (vs/jt
                  "merchantportalws"
                  "removeProductsFromPackage")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_start" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" true
            "type" "`$STRING`"))
        "name" "output_start"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/start"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "start")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_status" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "percentage"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "response_message"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "status"
            "req" false
            "type" "`$STRING`"))
        "name" "output_status"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`"))
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/status/{id}"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "status"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_update_product" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "allow_multiple_order"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "app_form_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "contract_needed"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "credentials_needed"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "description_key"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "name_key"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "prescreening_allowed"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "product_name"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "product_status"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "product_uuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "response_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "response_message"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "vendor_name"
            "req" false
            "type" "`$STRING`"))
        "name" "output_update_product"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "POST"
                "orig" "/merchantportalws/updateProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "updateProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinTecsMerchantPortal")
    "options" (vs/jm
      "base" "https://test.tecs.at"
      "entity" (vs/jm
        "merchant_portal_api_controller" (vs/jm)
        "merchant_portal_common_controller" (vs/jm)
        "merchant_portal_pam_contract_controller" (vs/jm)
        "merchant_portal_pam_document_controller" (vs/jm)
        "merchant_portal_pam_form_controller" (vs/jm)
        "merchant_portal_pam_mandator_controller" (vs/jm)
        "merchant_portal_pam_merchant_controller" (vs/jm)
        "merchant_portal_pam_package_controller" (vs/jm)
        "merchant_portal_pam_product_controller" (vs/jm)
        "output_add_product" (vs/jm)
        "output_create_product" (vs/jm)
        "output_detail" (vs/jm)
        "output_list" (vs/jm)
        "output_message" (vs/jm)
        "output_move_tid" (vs/jm)
        "output_remove_product" (vs/jm)
        "output_start" (vs/jm)
        "output_status" (vs/jm)
        "output_update_product" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
