;; BluefinTecsMerchantPortal SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "merchant_portal_api_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "account_number"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "additional_data"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "business_reg_number"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "city"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "corporateuuid"
            "type" "`$STRING`")
          (vs/jm
            "name" "country"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "merchant_category_code"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "merchant_email"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchant_name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "merchant_phone_number"
            "type" "`$STRING`")
          (vs/jm
            "name" "packageid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "packageorderuuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "password"
            "type" "`$STRING`")
          (vs/jm
            "name" "productid"
            "type" "`$STRING`")
          (vs/jm
            "name" "productid_acquirer"
            "type" "`$STRING`")
          (vs/jm
            "name" "reason_deactivation"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "reason_reactivation"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "sorting_code"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "state"
            "type" "`$STRING`")
          (vs/jm
            "name" "street"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminal_country_code"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminal_language_code"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminal_location"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminal_serial_number"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalid"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "terminalid_acquirer"
            "type" "`$STRING`")
          (vs/jm
            "name" "user_email"
            "type" "`$STRING`")
          (vs/jm
            "name" "user_phone_number"
            "type" "`$STRING`")
          (vs/jm
            "name" "username"
            "type" "`$STRING`")
          (vs/jm
            "name" "vu_nummer"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "web_shop_url"
            "type" "`$STRING`")
          (vs/jm
            "name" "zipcode"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_api_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/deactivateTerminal"
                "parts" (vs/jt
                  "merchantportalws"
                  "deactivateTerminal")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/reactivateTerminal"
                "parts" (vs/jt
                  "merchantportalws"
                  "reactivateTerminal")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/registerAdditionalTerminal"
                "parts" (vs/jt
                  "merchantportalws"
                  "registerAdditionalTerminal")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/registerNewMerchant"
                "parts" (vs/jt
                  "merchantportalws"
                  "registerNewMerchant")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_common_controller" (vs/jm
        "fields" (vs/jt)
        "name" "merchant_portal_common_controller"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/merchantportalws/logDeveloperInfo"
                "parts" (vs/jt
                  "merchantportalws"
                  "logDeveloperInfo")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/merchantportalws/version"
                "parts" (vs/jt
                  "merchantportalws"
                  "version")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_contract_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "language"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "productOrderUUID"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_contract_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/generateContract"
                "parts" (vs/jt
                  "merchantportalws"
                  "generateContract")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/uploadContract"
                "parts" (vs/jt
                  "merchantportalws"
                  "uploadContract")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_document_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "appFormFieldDescUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "packageOrderUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "productOrderUUID"
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_document_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/documentsList"
                "parts" (vs/jt
                  "merchantportalws"
                  "documentsList")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/downloadDocument"
                "parts" (vs/jt
                  "merchantportalws"
                  "downloadDocument")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_form_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "appFormFieldsDescUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "filter"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "language"
            "op" (vs/jm
              "create" (vs/jm
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "packageOrder"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "packageOrderUUID"
            "op" (vs/jm
              "create" (vs/jm
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "packageUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "productOrderUUID"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "type" "`$STRING`")
          (vs/jm
            "name" "productOrders"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "reasonOfReopening"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_form_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/applicationForm"
                "parts" (vs/jt
                  "merchantportalws"
                  "applicationForm")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/packageForm"
                "parts" (vs/jt
                  "merchantportalws"
                  "packageForm")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/reopenForm"
                "parts" (vs/jt
                  "merchantportalws"
                  "reopenForm")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/secretKey"
                "parts" (vs/jt
                  "merchantportalws"
                  "secretKey")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/submitForm"
                "parts" (vs/jt
                  "merchantportalws"
                  "submitForm")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/submitValues"
                "parts" (vs/jt
                  "merchantportalws"
                  "submitValues")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_mandator_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "clientSecret"
            "type" "`$STRING`")
          (vs/jm
            "name" "mandatorName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "notificationEmail"
            "type" "`$STRING`")
          (vs/jm
            "name" "packageUUID"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_mandator_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/createMandatorConfig"
                "parts" (vs/jt
                  "merchantportalws"
                  "createMandatorConfig")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/introduceMandatorPackage"
                "parts" (vs/jt
                  "merchantportalws"
                  "introduceMandatorPackage")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/selfRegistrationLink"
                "parts" (vs/jt
                  "merchantportalws"
                  "selfRegistrationLink")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_merchant_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "additional_data"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "businessRegistrationNumber"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "city"
            "type" "`$STRING`")
          (vs/jm
            "name" "companyName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "corporateUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "country"
            "type" "`$STRING`")
          (vs/jm
            "name" "currency"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "email"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "language"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "login"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "mandator"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantContractNumber"
            "op" (vs/jm
              "create" (vs/jm
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantName"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchant_category_code"
            "type" "`$STRING`")
          (vs/jm
            "name" "packageUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "packageorderuuid"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "phoneNumber"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "postalCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "productid_acquirer"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "region"
            "type" "`$STRING`")
          (vs/jm
            "name" "registrationNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "signature"
            "type" "`$STRING`")
          (vs/jm
            "name" "street"
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalIds"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "terminalid_acquirer"
            "type" "`$STRING`")
          (vs/jm
            "name" "vu_nummer"
            "req" true
            "type" "`$STRING`"))
        "name" "merchant_portal_pam_merchant_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/contractNumber"
                "parts" (vs/jt
                  "merchantportalws"
                  "contractNumber")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/registerAdditionalAcquiring"
                "parts" (vs/jt
                  "merchantportalws"
                  "registerAdditionalAcquiring")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/updateMerchant"
                "parts" (vs/jt
                  "merchantportalws"
                  "updateMerchant")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/registerMerchant"
                "parts" (vs/jt
                  "merchantportalws"
                  "registerMerchant")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_package_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "consumerUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "corporateUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "country"
            "type" "`$STRING`")
          (vs/jm
            "name" "descriptionKey"
            "type" "`$STRING`")
          (vs/jm
            "name" "filter"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "language"
            "op" (vs/jm
              "create" (vs/jm
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "nameKey"
            "type" "`$STRING`")
          (vs/jm
            "name" "packageStatus"
            "type" "`$STRING`")
          (vs/jm
            "name" "packageUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "sorting"
            "type" "`$OBJECT`"))
        "name" "merchant_portal_pam_package_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/availablePackages"
                "parts" (vs/jt
                  "merchantportalws"
                  "availablePackages")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/orderPackage"
                "parts" (vs/jt
                  "merchantportalws"
                  "orderPackage")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/orderedPackages"
                "parts" (vs/jt
                  "merchantportalws"
                  "orderedPackages")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/packageTemplates"
                "parts" (vs/jt
                  "merchantportalws"
                  "packageTemplates")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/updatePackageData"
                "parts" (vs/jt
                  "merchantportalws"
                  "updatePackageData")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "merchant_portal_pam_product_controller" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "consumerUUID"
            "type" "`$STRING`")
          (vs/jm
            "name" "filter"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "language"
            "type" "`$STRING`")
          (vs/jm
            "name" "merchantID"
            "type" "`$STRING`")
          (vs/jm
            "name" "packageOrderUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "pagination"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "productOrderUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "productUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "reason_decline"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "sorting"
            "type" "`$OBJECT`"))
        "name" "merchant_portal_pam_product_controller"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/approveProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "approveProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/declineProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "declineProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/orderAdditionalProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "orderAdditionalProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/productsList"
                "parts" (vs/jt
                  "merchantportalws"
                  "productsList")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_add_product" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "packageUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "productUUIDs"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "name" "responseCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "req" true
            "type" "`$STRING`"))
        "name" "output_add_product"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/addProductsToPackage"
                "parts" (vs/jt
                  "merchantportalws"
                  "addProductsToPackage")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_create_product" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "acquirerId"
            "type" "`$STRING`")
          (vs/jm
            "name" "allowMultipleOrders"
            "req" true
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "appFormTemplateName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "contractNeeded"
            "req" true
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "credentialsNeeded"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "descriptionKey"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "nameKey"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "prescreeningAllowed"
            "req" true
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "productName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "terminalTemplateName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "vendorName"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "xmlTemplateFile"
            "req" true
            "type" "`$STRING`"))
        "name" "output_create_product"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/createNewProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "createNewProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_detail" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "batch"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "lines"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "progress"
            "type" "`$OBJECT`"))
        "name" "output_detail"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`"))
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/details/{id}"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "details"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_list" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "items"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "pagination"
            "op" (vs/jm
              "create" (vs/jm
                "type" "`$OBJECT`"))
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "responseCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "sorting"
            "type" "`$OBJECT`"))
        "name" "output_list"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/list"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "list")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_message" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "responseCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "req" true
            "type" "`$STRING`"))
        "name" "output_message"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`"))
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/restart/{id}"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "restart"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`"))
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/stop/{id}"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "stop"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_move_tid" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "productOrderUUIDs"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "name" "responseCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "targetPackageOrderUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "targetProductOrderUUID"
            "req" true
            "type" "`$STRING`"))
        "name" "output_move_tid"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/moveTid"
                "parts" (vs/jt
                  "merchantportalws"
                  "moveTid")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_remove_product" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "packageUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "productUUIDs"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "name" "responseCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "req" true
            "type" "`$STRING`"))
        "name" "output_remove_product"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/removeProductsFromPackage"
                "parts" (vs/jt
                  "merchantportalws"
                  "removeProductsFromPackage")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_start" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "req" true
            "type" "`$STRING`"))
        "name" "output_start"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/start"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "start")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_status" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "percentage"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "status"
            "type" "`$STRING`"))
        "name" "output_status"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`"))
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/merchantportalws/batch/registerAdditionalTerminal/status/{id}"
                "parts" (vs/jt
                  "merchantportalws"
                  "batch"
                  "registerAdditionalTerminal"
                  "status"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "output_update_product" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "allowMultipleOrders"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "appFormName"
            "type" "`$STRING`")
          (vs/jm
            "name" "contractNeeded"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "credentialsNeeded"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "descriptionKey"
            "type" "`$STRING`")
          (vs/jm
            "name" "nameKey"
            "type" "`$STRING`")
          (vs/jm
            "name" "prescreeningAllowed"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "productName"
            "type" "`$STRING`")
          (vs/jm
            "name" "productStatus"
            "type" "`$STRING`")
          (vs/jm
            "name" "productUUID"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "responseCode"
            "req" true
            "type" "`$INTEGER`")
          (vs/jm
            "name" "responseMessage"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "name" "vendorName"
            "type" "`$STRING`"))
        "name" "output_update_product"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "header" (vs/jt
                    (vs/jm
                      "kind" "header"
                      "name" "authorization"
                      "orig" "authorization"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/merchantportalws/updateProduct"
                "parts" (vs/jt
                  "merchantportalws"
                  "updateProduct")
                "select" (vs/jm
                  "exist" (vs/jt
                    "authorization"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinTecsMerchantPortal")
    "options" (vs/jm
      "base" "https://test.tecs.at"
      "entity" (vs/jm
        "merchant_portal_api_controller" (vs/jm)
        "merchant_portal_common_controller" (vs/jm)
        "merchant_portal_pam_contract_controller" (vs/jm)
        "merchant_portal_pam_document_controller" (vs/jm)
        "merchant_portal_pam_form_controller" (vs/jm)
        "merchant_portal_pam_mandator_controller" (vs/jm)
        "merchant_portal_pam_merchant_controller" (vs/jm)
        "merchant_portal_pam_package_controller" (vs/jm)
        "merchant_portal_pam_product_controller" (vs/jm)
        "output_add_product" (vs/jm)
        "output_create_product" (vs/jm)
        "output_detail" (vs/jm)
        "output_list" (vs/jm)
        "output_message" (vs/jm)
        "output_move_tid" (vs/jm)
        "output_remove_product" (vs/jm)
        "output_start" (vs/jm)
        "output_status" (vs/jm)
        "output_update_product" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
